### ISSUE TITLE
Make the Project manager data editable

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#176]
I started this, but I am stuck at making the "Edit Info" button work.  See Line 13 of top.php.

**Comment by bsaiken** [comment]
I made some changes to this UI.  The most important being the change to

**Comment by bsaiken** [comment]
@damirius 
This would also be a good Issue to tackle after implementing #421.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

This Issue is almost done, few things I wanted to ask before I send this to function review.
I had to add on click code for top menu button in utils.js, I know this isn't the right place, but we need to have that code on every page, we don't need whole pm_manager.js actually, but we need that function which triggers on click. If you have any ideas where to put this please do tell me.
Since we will have different types of users, we can modify top menu to show different button for different types, for now it works for project managers.
Column width can be changed if needed of course.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

You can create a `top_menu.actions.js` instead of using the `pm_manager.js` and use it just to handle the actions from the top menu that, in any scenario, will need to be available everywhere.

Add the script in the header.php template.

In your scenario, you need to load the `project_manager/showForm?pm_id=X` url. Am I correct? Of course, you can plan to make it generic to work with technician, admin (for each role basically. use of switch...case?).

Let me know if you need more help.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
When we are working on top menu actions, we will need to keep the top menu configurable.  Right now, the glypicon-user icon is for editing PM info.  But, in occurred to me, that this gylphicon could be used to edit the personal info for whoever logged in, and that may be a Project Manager, Technician or Service Provider.  It might even be handy to have this glyphicon do something for the admin login.
Jeremie and I can discuss this tomorrow and see how we want to handle it.

**Comment by damirius** [comment]
@bsaiken @FWAJL 
Yea that's the plan, to use the same button for multiple page links based on the type of the user. There are few ways to do this, send user role to top.php menu template and create button with different id and with different data-pm-id attribute.
Currently we have id="view_pm_info", we can change that to id="view_ft_info" and add attribute data-ft-id="xxFTIDxx" instead and to add new click trigger to "view_ft_info".
Other option is to add different link in the same js function based on the role.
Third one is to create default controller method, i.e. user/showForm?id=3 where we will check the users type and show form based on it.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

***Option 3*** is a better one. You will need a php module of each type and you will show the proper module (Pm, admin, FT, service provider...) according to the user role. Similarly, you want to include the javascript file handling updates to the user info to be generic so instead of a `pm_manager.js`, you would have a `user_manager.js` calling the UserController method to edit the data and the logic would be in the Controller/Helper.

Don't delete the pm_manager file. We will use it for the Admin implementation.

What do you think about my idea about the `top_menu.actions.js` file? Since we have the top menu on every page, I think it is a good solution.

Thank you.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I'm OK with Option 3.  The glyphicon will be used by the Project manager to edit their information.  I see the form is already built: `/views/Pm/Modules/pm_form.php`.  
Then, users of other role designations can edit their info.  Field Technicians, Service Providers, and Clients will all be able to edit their personal information.  In theory, the admin could also edit their information, but no admin information needs to be saved, so for admins it would be a dead link.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've added User controller for this so we can later add new forms for the same page for different user types. Functionality should be the same for now, since we don't have other user types yet. You can see the form here `user/showDetails` or just click on the icon in the top bar. I've also added top_menu.actions.js to the header like Jeremie suggested.
I see that we already have this as the testing task in the google doc under "Login and PM"->"PM Editor", so I'll leave it like that.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Yes, I have set up a lot of the testing already.  But, going forward, always look.
The function here is great - thanks.
I would like you to clean up the formatting.  Use the 5 - 2 - 5 bootstrap column structure, so the form is in the left column and the button is in the middle.  Change `pm_button_edit` to "Save".
The CSS for the forms should already be prepared.
This way, will have a consistent look to all our forms.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

OK, made those design changes and some minor changes to module loading depending on the user type.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Perfect - thanks.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I just checked this on the feature_damir branch, and it is not working...
The form appears, but when I click the "Save" button, nothing happens.
Am I missing something?

**Comment by FWAJL** [comment]
@bsaiken 

We shouldn't comment here about the forms. See here: #403

**Comment by bsaiken** [comment]
@damirius  @FWAJL 

Damir,  Please disregard Jeremie's comment.  I think he misunderstood...
Can you please check this?  
When I navigate to `/user/showDetails`, I see this:

![screen shot 2015-04-06 at 12 48 58 pm](https://cloud.githubusercontent.com/assets/8228624/7011125/50509d9e-dc5b-11e4-9cdf-250a002efb08.png)

However, when I click the "Save" button, nothing happens.

**Comment by damirius** [comment]
@bsaiken 

Clicking save will edit the user info and reload the page, hm do you see any error message popping up? Did you try filling up all fields, I know that they can't be NULL, but they should be set as empty strings ("")

**Comment by FWAJL** [comment]
@damirius @bsaiken 

See the details in the POST request after clicking "Save":
![screen shot 2015-04-06 at 22 13 24](https://cloud.githubusercontent.com/assets/7524388/7011486/d23564d6-dca9-11e4-8f17-d5066c93862d.png)

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Yes, thanks. I've changed it. I see that you've changed something on the `UserController` line 36 which broke it, I passed the pm object instead of the whole pm session, so it should work now.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I think it's fine to release this.  I would have caught the bug in unit testing, and I just got lucky I caught it prior to release.  I will be doing unit testing later today.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
This is working, but I re-opened because I noticed a problem.
We need a re-direct after clicking "Save" - the page does not refresh. 
Re-direct to the home page (/project/listAll).
The array needs to be updated, too.  I see the database is updated, but when I refresh nothing on the page is changed - neither the pm_form contents, nor the header info (with the pm_name).

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've tested it in Chrome, Firefox and Safari. In all those browsers, page is successfully refreshing after saving data and it's updating the session as well. You can check it out in this video, it's not the best quality but you can see that the page is refreshed and updated data is read into the form, also you will notice that name is updated in the top bar.
https://drive.google.com/file/d/0B7Laiv0PjSvDQlNDYU9PRFBvcW8/view

The reason that we are refreshing instead of redirecting to some specific page is that this user/showDetails page can be accessed by any user. So for example if admin wants to edit his password/hint, or technician or some other type of user and we redirect him to /project/listAll we will cause some problems.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

I think we can do what Brian asks for. Just do a switch in `UserController->executeEditCurrent` based on the value of `$this->app->user()->getUserType()`.

Then for each type, we will have a Helper method that does what you have done lines 60-70. In this case, the helper is the PmHelper.

Then, on return of the method, you can set the url to go to next: `$result["returnUrl"] = "project/listAll"`.

What do you say?

**Comment by damirius** [comment]
@FWAJL @bsaiken

Yes, we can change the 'redirect' url based on the user type. I can implement that.

But as I see here, that currently page does not refresh and on manual page refresh, session data isn't properly set, so submitted changes aren't taking place. I can't reproduce that bug, since my automatic page reload works. I would like to see what's up with that. Since page isn't redirecting/refreshing I guess that response json is malformed, probably because some error outputs which are caused by problems with the code block which comes after `$manager->edit` line. Now, I would like to see the output of `user/editCurrent` ajax call so I can try and fix that. If I just change redirect url based on user type we will still have the same problem with no redirects and session data saving there.

I would like to hear from Brian if he can get us some more details about this, I can change the redirect url after that.

In any case thanks for your suggestion!

**Comment by bsaiken** [comment]
@damirius @FWAJL 
This is now working on the live branch.
I am having issue testing the feature branches locally.  Not sure why.  Jeremie and I may need to sort that out.
