### ISSUE TITLE
Upload and view technician photos

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#249]

**Comment by bsaiken** [comment]
I am going to make a SOW for this.

**Comment by FWAJL** [comment]
@baiken : ok

--
Jérémie Litzler

**Comment by WebDevJL** [comment]
Related to #397 : table structure and more specifications.

**Comment by damirius** [comment]
@bsaiken

Can one technician have more than one photo?

**Comment by bsaiken** [comment]
@damirius 
Good question.  For now, let's limit technicians to one photo, and always display it in the `/technician/showForm` view.  This is the equivalent of their "Profile" picture in Facebook.  It should be sized to fit the right hand column space available.
Just to complete the thought, Locations can have more than one photo.

**Comment by bsaiken** [comment]
I don't know if a formal SOW is needed for this.  Let me know if you need more details.

**Comment by damirius** [comment]
@bsaiken

You can check out new commit on the feature_damir branch. I had to split upload module into two separate modules, one for document view and one for document upload box. This way we have more options regarding layout. For example we maybe want to show only upload box or only photos without the option for uploading new ones.
For function review you can select the project and go to Technician->List all.
After that right click on some of technicians to edit it.

If you click "Click to upload photo" button, drag&drop box will appear on the side. You can choose photo to upload and title/caption for it. After you assign the photo to technician you can click "Click to upload photo" button again to upload new photo and replace old one.
Clicking on the photo will activate lightbox. Note that caption is defaulted to name of the uploaded picture if you leave it blank when you upload it.
Since we use the same module for Location Map Info window, you'll see title/caption input box there too. It will store the value in the db, but it will not be shown as the caption when you view the photos there. Since we have other issue which will require to edit that part of the map info window I'll see that I implement then.

**Comment by bsaiken** [comment]
@damirius 
We don't think we need the `Click to upload Photo` button.  It's been there as a placeholder all this time.  I'd rather the Drag&Drop box always be visible.  If the photo is there, we don't need it, since Technicians have only one photo.  If we deleted the photo, then we'd see the Drag&Drop box again.

I meant for you to put the photo in the div `id="documents"`.  The div `class="col-lg-7 col-md-7"` is not needed.

**Comment by damirius** [comment]
@bsaiken

OK, how do we delete the photo? New button in the form for photo removal or something else?

Also class col-lg-7 was needed in the case when we show both photo and upload box. I am aware that you don't need it now if we are showing either upload box or the photo.
Also as I said I split the upload module into two parts, one for documents display one for uploading since we will need to use sometimes one module and sometimes another. For example Location Info window uses only upload box. That said photos are in the div#documents.

**Comment by bsaiken** [comment]
@damirius 
If you need to show the photo and the upload box, I'd rather the upload box be below the photo. I did not like how the photo was slid to the right.
I don't know how you had intended to delete the photo because when I tested, uploaded photos did not display.

**Comment by damirius** [comment]
@bsaiken

I don't need to show both if we want the functionality to delete photos before uploading new ones. I've added new hidden field `itemReplace` which can be true or false in the `upload_file` module. It is set to true for technicians, so when we upload the photo again, old one will be deleted and new one will take it's place.
Are you experiencing some issues with this since you mentioned that uploaded photos did not display?

**Comment by damirius** [comment]
@bsaiken

When you go to technician edit, you'll see photo on the right side column if you already uploaded one or upload box if you didn't. When you upload it, image will be loaded and you'll see little 'x' on the right. If you click it image will be removed and upload box will popup again.

**Comment by bsaiken** [comment]
@damirius 

I have now checked Chrome and no photos display anywhere, so I cant complete the function review.  

I have some other obligations today so I may not be able to do more in-depth testing to help you out until tomorrow.  You can move on to another Issue if you like.
