### ISSUE TITLE
Add alphabetization for Technicians list

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#273]

**Comment by WebDevJL** [comment]
@bsaiken : I will start this by using the database filtering solution and I will apply it every list (because the select method is common to all).

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I'm not sure how can we guess by which field should we order the results. For example in `client` table we have both `client_company_name` and `client_contact_name`, so we must choose. My suggestion is this, if we don't want to add modified `selectMany` method to each DAL we can implement some `GetSortByField` method in `Entity` base class and set it to return `false` by default. When we call default `selectMany` method in `BaseManager` we can call `$object->GetSortByField()` method, if it returns `false` we continue as we did before. On the other hand if we override that method in some class that extends the `Entity` class, for example `Client` and add `return "client_company_name"` we can then append the "orderby" string to existing select query: `$order_by = "ORDER BY ".$object->GetSortByField();`

**Comment by bsaiken** [comment]
@damirius 
Would it help if I gave you the sort criteria fields?

**Comment by damirius** [comment]
@bsaiken

If we do it like I suggested we would need it anyways for each table in which we want to have some sorting other than default (default is by primary key/id).

**Comment by bsaiken** [comment]
@damirius 

In that case, we will do it on a case by case basis and I will make a separate Issue for each case.  I changed this Issue to the new Milestone "Alphabetization".
To start, for this Issue, Add sorting to Technicians based on technician.technician_name.

Obviously this will work for active or inactive Technicians in `/technician/listAll`.  Would it be a separate Issue to apply the sorting to the lists of Technicians that are on the `/task/technicians` url?

**Comment by damirius** [comment]
@bsaiken

You can check it out on feature_damir. Task technicians ordering is more or less done in php helpers, I've done that part so you should be able to see ordered technicians in the tasks also. As you know `task_technician` table doesn't contain actual technician name since it's used as relationship table, so when we "merge" `task_technician` results with `technician` table data we just need to iterate through `technician` results to preserve the order of results we specified in that entity. I don't want to bore you with this technicalities, it's not a lot of work to set up proper ordering so it's not really a problem.

Also I mentioned this Issue in the commit since it's initial commit for this milestone and this stuff. We can use other issues for other cases like you suggested.

Thanks!

**Comment by FWAJL** [comment]
@damirius 

I like how you figured out a solution. It works well and is really flexible. Now, we need to think about a Linq-like method to order the Session list too. I have been looking into this for a while because it can be really handy.
In fact, we retrieve at first the list ordered in the database but if we change a technician name and that the order changes, only logging out will order the list properly (new database call).

Let me look at this quickly and I will come back to you.

Thank you for your excellent work.

**Comment by bsaiken** [comment]
@FWAJL 
The chance a Technician's name would be changed in the middle of a session is small, and the consequence is no big deal, so fixing this can be set as a backburner Issue.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

Ok. That's fine with me.
