### ISSUE TITLE
Duplicate entries when moving anaytes to Project analytes list

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#413]
![screen shot 2015-01-19 at 3 44 22 pm](https://cloud.githubusercontent.com/assets/8228624/5809120/2db237b6-9ff2-11e4-89ab-3b5ecae85292.png)

**Comment by WebDevJL** [comment]
@bsaiken : duplicated are not really. plus you removed one since you took the screenshot.

See attached.
![issue413-2](https://cloud.githubusercontent.com/assets/3506074/5813449/cca9777c-a07d-11e4-9613-731c4beb9d11.png)
![issue413-1](https://cloud.githubusercontent.com/assets/3506074/5813450/ccb0de18-a07d-11e4-9726-8b938cbffab7.png)

**Comment by bsaiken** [comment]
You need to add the constraint so there are no duplicates on  field_analyte_name_unit.
Similar for lab analytes.  If the user tries to add the same analyte a second time, we should just ignore this.  Coming up, we will add a popup alert box so the user knows this.   Also, when we add the autocomplete feature, there will be less likelyhood of a duplicate entry.

**Comment by WebDevJL** [comment]
@bsaiken : ok. Will look at this.

**Comment by bsaiken** [comment]
@FWAJL 
I think this Issue is deprecated and can be closed.

**Comment by FWAJL** [comment]
@bsaiken 

Indeed. Closing.
