### ISSUE TITLE
Front-end escape single quote

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#446]
escape the single quote from user inputs to avoid problems with the sql queries.

The updates must take place in the dataservice.js file, just before calling the PHP scripts.

**Comment by FWAJL** [comment]
Related to #425

**Comment by bsaiken** [comment]
I tried single quotes for the 2/2/2015 unit tests.  Surprising result.  For adding a Technician (only), the "Add" button caused the site to freeze up, but the technician name (including the single quote) was added.

![screen shot 2015-02-02 at 12 44 31 pm](https://cloud.githubusercontent.com/assets/8228624/6007706/7901a912-aad9-11e4-84c6-59af90057dbe.png)

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Single quotes shouldn't be escaped in JSON only double quotes and control char (" and \), see here http://www.json.org/.

If you want to sanitize inputs it would be best to do it where it counts and that's before executing queries, since sanitizing all of the ajax data can cause more problems than it can prevent.
This should be done in DALs that we use including BaseManager class.

Since we are using PDO, we can use `prepare` method along with params, then use `bindValues` or bind them inside the `execute` method. Maybe it's too late for that since there is already lot of code written for DALs. Other option is to use `quote` method of PDO class which is essentially `mysql_real_escape_string` function but it also wraps values in quotes.

I can work on implementing PDO::quote to all values in all DALs, there isn't so much work there, just boring copy/pasting, or we can try to convert existing code to use `prepare`/`execute` methods when needed which is a lot of more work but better in the long run.

Tell me what do you think.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

I agree the PDO (back-end side) is better. 

How much time do you think it would take you to use bindValues solution? Most of the DAL classes use the BaseManager class so in reality, it is mainly that one to do.

If it is too risky, then go for the PDO::quote solution.

**Comment by damirius** [comment]
@FWAJL @bsaiken 

I don't think that it's that much. We got number of DALs which use their functions instead of base ones, but I think I can do it fast enough. I'll start now, I'll keep you updated if I notice something unusual.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

Great! Thank you for taking care of it!

**Comment by damirius** [comment]
@bsaiken @FWAJL 

There is quite a lot changed here, I spent some time testing all of the existing pages, listings, forms, file uploads (master/user forms, ft/location pictures) and so on. I ran in some problems on some controllers, mainly because we have some fields in our tables which can't be set to null, but we didn't assign them values on the insert, so keep your eye on that. There is possibility that I missed some things, but I guess we have that testing procedures because of that.

**Comment by FWAJL** [comment]
@damirius 

Already done? Man, you are fast!!! We will look into it. Thank you for your work :100: 

After looking quickly at your commit, if you need to set some field to string values, you can do it directly in `CommonHelper->PrepareObject`, don't you?

**Comment by damirius** [comment]
@FWAJL 

Yea, `PrepareUserObject` is setting undefined values to null by default, which I think is OK way to go. Since we don't know the type of the DAO parameter (field) from there I opted not to set it to "" (empty string) since I guess it can cause some problems if we set all undefined fields to "" because some of them can be different types. So I edited some `add` methods in some controllers where we don't send all required fields through json and set them to empty strings if there aren't sent.

**Comment by FWAJL** [comment]
@damirius 

I knew you would say that. I think the fix for that would be to update my Dao class generator to create typed members from the database definition. Didn't try to see if it is possible in PHP.

Your solution is fine for now.

**Comment by damirius** [comment]
@FWAJL 

I'm used to annotations for those things, but we need good parsing method for that and some work.
`ReflectionClass` contains some useful methods like this one http://php.net/manual/en/reflectionclass.getdoccomment.php
If you have any ideas do tell me, maybe we can come with some nice solutions for this.
In any case it will take some time to implement all that, so we will have to check what's the most effective solution for now.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I am unable to login as a PM.

![screen shot 2015-04-23 at 8 31 05 am](https://cloud.githubusercontent.com/assets/8228624/7300792/2f7b0b46-e993-11e4-9458-0f1a42b7a51a.png)

**Comment by damirius** [comment]
@bsaiken

If you are on feature_damir branch, keep in mind that newest commit is for Issue #734 and with that commit you will have to update your database with the newest SQL script '2015-04-23.sql'

I'm not sure that this will fix it, but from the error it seems that `UserProjects` aren't set properly which can be caused by the lack of the `project_is_default` field in the db.
Just wanted to make sure that update was ran.

**Comment by bsaiken** [comment]
That's likely it. I had not updated the database today.

**Comment by bsaiken** [comment]
@FWAJL @damirius 

Jeremie, I pulled the new database and I still get the same error.  As it is, I cannot function review Damir's work.

Any ideas?

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I completely re-installed the site.  The error only happens on the feature_damir branch.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

My MAC has gone crazy so I can't test locally for now. I tested all Damir's updates up to the one for this issue at lunch time and I can say it is quality work. 

For this one, I shall look at it tomorrow as he said to watch out for functions that might not work.

Also, have you run his SQL script locally? The current live database doesn't have his script yet.

**Comment by bsaiken** [comment]
@FWAJL 
grrrr....your scripts don't work on my machine.  I will reply here again if I can get the script to work.

**Comment by FWAJL** [comment]
@bsaiken 

Brian, it is not my script. It is Damir's. He did an update to the project_manager table. You need to run his script to do a proper function review.

Have you tried? Please try. Thank you.

**Comment by bsaiken** [comment]
@damirius 
Where is the SQL script `2015-04-23.sql`?
Can't find it anywhere.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

Here: https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_damir/Database/Scripts/Updates/2015-04-23.sql

**Comment by bsaiken** [comment]
@FWAJL @damirius 

Finally...

I just added "Joe's hauling" as a service provider successfully.  If I understand correctly, that is a successful function review.

Thanks!

**Comment by WebDevJL** [comment]
@damirius @bsaiken 

Having limited access to my computer, I can't give you the specific unit tests so I'll describe what you need to test :

Everywhere you have an input that is a string, test it. 

For project, technician, location, task, analyte, etc... And you should test the add and edit functions of each. 

I hope that's clear enough. 

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
I tested this all kinds of crazy ways - I was unable to create an error.  I even tested impossible entries involving a single quote.  Nary a problem.
I think it is ready for code review.
Brian
