### ISSUE TITLE
Milestone D – Prompt Boxes

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#481]
Decription:
Prepare a widget to display prompt boxes at specified locations as shown in Attachment A. Prompt boxes require input to be stored in the database or on a web form. In some cases, a redirect will be required to continue to the correct page. Content of prompt boxes (instructions) are to be in an editable xml file.

@gsouvik  

Commit code for the milestone D under this issue. 

Thank you.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
I was working on this milestone and had a question related to the "Analyte" section of the requirement as described in attachment A. It describes Analyte > List All >> Item > Edit. But there is no context menu in the active list and there is no edit option on the context menu showing on the inactive list. My question is, do I have to create the context menu wherever applicable and add options to "edit" in those?
Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
The Analyte UI is still being developed (we needed to make changes).  I thought it would be done by the time you stared Milestone D.  Save this until the end, then if we are still not ready for you, I will have you move on with other issues.  
Thanks

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Thank you for the information, yes I've started with the other portions of the milestone D. Shall keep you updated with the progress.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
"Task" section of the milestone is completed and pushed to feature_popup. Continuing with the other portions and shall update again shortly.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Can you be more specific?  I just checked the feature_popup branch and I do not see these modifications.

**Comment by gsouvik** [comment]
@bsaiken 
As per attachment A, The portion of the requirement which specifies the Task related changes, are implemented (please refer to the image for the details of the requirement).
Steps to test:
1) Click on "Add this task". If task name is empty the system presents a prompt box asking the user to enter a new task name.
2) When user enters a new task name and clicks Ok, the system checks if the task name is unique. If yes, then adds the task name and presents the edit screen with the task name populated.
3) If the task name is already used, it presents an alert box stating the same.
4) Also if the user enters a task name on the main showForm screen and clicks "Add this task", it checks for the uniqueness of the name as described in point 3 above.

Please review and let me know you feedback. I'm working on the other sections of milestone D and shall update you shortly.

![screen shot 2015-02-17 at 12 13 28 am](https://cloud.githubusercontent.com/assets/2292482/6217444/ebc845a8-b639-11e4-9c11-6ab5fbd93af5.png)
"

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
I understand.  You applied the popup to "btn_add_task", which is in the task/showForm URL.  That is fine, and it works correctly.  Please do not change this.
However, I wanted the popup applied to "btn-add-task-manual", which is the left menu button.  Please add the popup there.
Brian

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Ok, I understand the requirement now, I have a quick question. As the entire left menu is accessible throughout the user session, someone could directly click Task > Add while on any other screen. Do you want the system to first navigate to the actual showForm page for the Task and then automatically show the prompt box? Because, adding a task is dependent on project selection (setting it current project). So anyone could just log in and directly click on Task > Add without setting a project as current project. How should the system behave in those cases?

Thanks,
Souvik

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
You are correct.  This should not work if a Project has not been selected. In order to complete the Milestone, manually select a Project.  I will open a new Issue to make sure a Project is pre-selected on login.  
When I wrote the SOW for the popups, I knew the list was not comprehensive, but this one I did not catch.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
I apologize, my mistake.  The conflict you are talking about is resolved by lines 5, 6 and 7 of Milestone D.
I didn't miss it after all.

**Comment by gsouvik** [comment]
@bsaiken Thanks for the clarification regarding the requirement.

@FWAJL Loading that prompt box from any left hand menu would require it to:
1) Load a module (the view of the promptbox) globally for every screen.
2) Fetch the title, messages for the prompt box from the xml and keeping it ready globally, because we don't know when the user would click "Task > Add" and on which screen the user would be at that point.

I need your suggestion regarding the following:
1) Can you please let me know if some "App controller" sort of thing exists in our system, where I could handle the "global loading" of the modules/messages.
2) Or, I should write the logic on every controller separately.
I hope I was able to explain my question, please let me know, else I'll try to describe it in more details.

Thank You

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Line no 3 of milestone D is coded and pushed to feature_popup. The requirement was for copying an existing project into a new one with proper validation.
I've implemented this on both - the context "Copy" menu and the "Copy" button on the view screen. Please review and let me know your feedback.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
The front end looks great.  Would it be possible to update the breadcrumb?  Once I have created the new Project (the copy), the breadcrumb says "Add new Project" - which leads me to think I still need to do something, but in fact the new Project has been created.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
1) Project copy feature - breadcrumb is now getting updated after the copy is complete to reflect the newly created project.
2) Task copy feature - implemented, this is as per line 4 of milestone D.
Please review and let me know. 
Thank you.

**Comment by FWAJL** [comment]
@gsouvik @bsaiken 

I'm starting the review. Thank you for your work, Souvik.

**Comment by gsouvik** [comment]
@FWAJL @bsaiken 
Milestone D is quite big and has around 7 points. Out of those only 3 are completed. I'm releasing as each point gets completed. Also I wanted to know your suggestion regarding point 2 in my previous message. 

So just wanted to update that this milestone is still in "dev" status, and please let me know your thoughts about point 2 when you have a chance.
Thank you.

**Comment by WebDevJL** [comment]
@gsouvik 

Thank you for letting me know. 

I think we'll create separate issues for eah next points. You'll commit the code under those. 

I'll talk to @bsaiken regarding this and will confirm everything. 

Keep up the good work.

**Comment by FWAJL** [comment]
@gsouvik 

Please find the issues created [here](https://github.com/FWAJL/FieldWorkAssistantMVC/milestones/Popups%20UI)
