### ISSUE TITLE
Mapping - Milestone A

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#520]

**Comment by damirius** [comment]
OK, so I've added maps for Selected Project/All Project's Locations/Task Locations. 
I also had to rewrite some parts of the All Projects map action. Since I had to use project_active field to show different marker icon I added new helper method which I used for both Selected Project map and for All Projects. Where I send both project object and facility object instead of just facility ones. This will work with 1:1 relation between facilities and projects, since we need "active" field for every marker and facility table doesn't contain it.

I wanted to do some things differently so I'm writing here to ask you for advice. I saw that there was maps.js file in the service directory, I've reused it's code for every map, but since I need some different parameters in each of these maps I had to make copies of it and link them like that. I see that js_files in routes.xml have "use" attribute which is set to "html". What is it used for? What I'm trying to ask is if there is some way to dynamically modify js files based on some parameters sent from controller or something like that? If it is, I could reuse maps.js for all of the maps and just change few js variables there based on the route/php parameters.

I've also changed ajax request params which that maps.js service is sending, because I wanted more flexibility with that. For example I had to send two objectTypes with some property names linked to them, so I opted for plain js objects because I can use them as associative arrays. Problem is that if I send just js object under properties Post parameter HttpRequest class brakes, so I used Json stringify to send it like a string and decoded it in controller. I see that there is retrievePostAjaxData method in HttpRequest class. Maybe I can somehow use that instead?

As far as the other things go. I modified mostly MapHelper, just added one method to CommonHelper. You can also check LocationHelper, I've changed GetProjectLocations, I think that part with filtering task locations was bugged.

I've added marker icon links in config, they are linked to the google's public icon libraries, we can change that but in any case I would rather just link local png files than use fuse tables just for the few icons.

I probably forgot some things I wanted to say, but when I remember them I'll let you know here. 

/cc @bsaiken @FWAJL

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I have checked the front end against the SOW and all requirements are met.  
Waiting for code review.

**Comment by damirius** [comment]
@FWAJL @bsaiken 

I still have few things to change. I want to remove few things that weren't necessary in the code and I want to combine all map js files into one. I just pushed that so you can take a look and tell me what do you want to see changed since I'm probably finished for today.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Keep in mind that I review the front end and Jeremie reviews the code.  I would like to check the front end first, before Jeremie reviews.  If we need to go through several rounds of review, because of code teaks, that's no problem.  Just keep the "assignee" updated, which i think you did.

**Comment by damirius** [comment]
@FWAJL @bsaiken 

I've updated some code in the map controller mostly and reorganized map js files. I also found some bug with task locations, since I didn't preload them in sessions before, like I do with regular project locations.

I also wanted to ask about js redirects, since it's stated that I need to redirect user in project_manager.js and location_manager.js when they click on the map links. I assume that means when current task or current project isn't set and they want to access task map or current project/locations maps. Maybe I'm wrong there. If someone can clarify that for me that would be great. 
I already have php redirect set in place when user wants to access Selected Project or All Project's Locations, if the current project isn't set they will be redirected to project/listAll to set it up. When they try to access Task Locations map, they will be redirected to project/listAll if they didn't set up current project or to service/listAll if they didn't set up current task.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

The "current task / project" will being taken care of with the popup dialogs. It is under development at the moment. In general, avoid using redirect like you did in MapController at lines 38-42, 60-64, 82-90.

At the moment, we select a project or a task to avoid the exceptions.

At the moment, the task locations are loaded when you load the url "task/locations". Have a look to the TaskLocation controller, method manageLocations.

Regarding the review of your code, I am doing it but there is a lot to look at and I still have to think about the questions you asked. Please bare with you a little longer :) The questions about using one maps.js file is very good and I will try to answer the question on how to do it once I have looked at it.

Thank you.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

I like the way you thought about and did the generalization of the map js file. More about it soon.

**Comment by damirius** [comment]
@FWAJL 
I'll remove php redirects with the next push. 
Task locations are properly preloaded now, like you suggested I took a look at the task controller to see how are locations loaded there and used the same helper method to load them in the map controller action. That was one of the changes in the previous commit. 

Also wanted to say that I'm not expecting you to review my code as soon as possible, I know it can be long process. I often write too much text on these "status reports" since I use them as the reminder for myself too.

Thanks

**Comment by FWAJL** [comment]
@damirius 

Yes, I saw the new code. I'm glad you are finding your way around easily. Keep it up :+1: 
I'm always here if you need help.

More soon.

Thank you.

**Comment by FWAJL** [comment]
@damirius 

I hope you are doing good.

Here is the point to look at in my review to finish the milestone:

1. In MapController at lines 38-42, 60-64, 82-90, please remove the redirect if statement. This will be taken care of with the popup dialogs. In general, avoid using redirect.
2. In MapController at line 137, you build the list of markers. However, if a project has no facility coordinates, a marker without coordinates is added and it results with an error in the gmaps.js execution and the map is not centered in the bounds of the correct markers. Please add a check in MapHelper::CreateFacilityMarkerItems to add a marker only if it has coordinates.
3. In MapController at line 253, you list the markers for project’s locations. Can you please set the center to the project’s facility coordinates if they exist when there are no project locations, or to the default center position otherwise?
4. In MapHelper, method CreateLocationMarkerItems, please add a check to add a marker only if it has coordinates.
5. In MapHelper, method CreateTaskLocationMarkerItems, please add a check to add a marker only if it has coordinates.

Let me know when you are done.

Thank you for the brilliant work so far.

**Comment by damirius** [comment]
@FWAJL 

Hi, I am doing well. Thanks for asking. I was working on some Milestone B stuff which I have stashed so we can move on it quickly when we finish this up.

1. Removed all redirects. I'll avoid adding new controller redirects from now on.
2/4/5 These 3 tasks are almost the same, I've added small check in MapHelper before pushing elements in the marker array.
3. I thought of that while I was working on this stuff for Milestone B. I had to add new request param called "defaultLocation" which I used to fetch proper object and property names of that object from session. You can see on lines 230-233 that I'm removing it from properties array, because I don't want to show the actual marker for facility on that map. After that you can see on lines 250-255 that I'm checking if there are no items in markers array and if not I'm calling old helper method BuildLatAndLongCoordFromGeoObjects which returns only lat and long. If there isn't any (valid) facility location and there are no markers map will use default position from the config file. Like on any other map, if there is 1 marker we will center the map on it and if there are more than 1 markers we will set bounds using all of them. That part is in js file.

Thanks

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I would like to clarify a couple of Jeremie's comments. 

2. Note that in order to create a Project, the Project MUST have a Facility address, and Milestone E will automatically create a lat/long from the address.   Therefore, it will not be possible to have a Project with no Facility coordinates.  Consider this in determining if the check in CreateFacilityMarkerItems is necessary.

3. The map center for Locations, when none of the Locations have coordinates, is always the Facility lat/long.    Since Facilities MUST have coordinates, the latter requirement, of a "default" center is not really needed and the default Facility zoom level can also be used.

In case it's not completely clear:  Locations can, and often will, have no coordinates.  All Locations shall be listed in the sidebar, as described in Milestone B.  Then, in Milestone C, we add the ability to place sidebar Locations (those without coordinates) on the map.  

Just as an FYI to help with the greater perspective:  In further development of the site, Field Technicians will be able to "mark" Locations (those without coordinates).  Using their smart phone or tablet device, they can use their Geo-referenced present location, and their manual identification of the Location name, to assign the Location the Geo-referenced coordinates.  In some cases, there do not even need to be Locations in the database to mark the coordinates.  In my prior park bench example, say you are assigned to map the location of every park bench in Pancevo.  You could physically go to each park bench, mark it and give it a name (or allow the website to generate a name automatically, like ParkBench-1, ParkBench-2, etc.).
