### ISSUE TITLE
Mapping - Milestone B

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#521]

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Do you have some images I can use for the sidebar icons, "select items", "add marker", "draw line or shape" and "measure distance and areas"?

Thanks

**Comment by bsaiken** [comment]
@damirius 
I thought they were standard.  Give me just a little time...

**Comment by bsaiken** [comment]
@damirius 
As long as the icons here are public domain, I would use these.
http://www.gstatic.com/mapspro/images/icons-toolbar-002.svg

**Comment by damirius** [comment]
@bsaiken 

Thanks!

**Comment by FWAJL** [comment]
@damirius 

Keep in mind that if the milestone is too large or if you have to change a lot of code, let's discuss to split it into sub issues so that the code review for a first sub issue can be done while you continue next sub issues.

We will work more efficiently that way.

Thank you.

**Comment by damirius** [comment]
@FWAJL 

The thing is that I already started working on this while you were reviewing code for Milestone A, so a lot of the things are done already. This milestone B is a lot of similar to the milestone C, so I'm currently finishing up js code which will have all this functions integrated so when I start working on next milestone I can focus more on PHP and just add few ajax calls for data saving.

In any case don't worry, I'll push my changes in the next couple of hours so you can review them.

Thanks

**Comment by FWAJL** [comment]
@damirius 

Thank you for the update. You can take your time. We realized for another task (popup) that a milestone had to be split for an easier code review.

In any case, I won't look at the code until next week anyway. 

Continue the good job!

**Comment by damirius** [comment]
@FWAJL 

Since you mentioned popup prompts, I need to use few popup windows for milestone C. First one I'll need is one for entering location name, description and photo when adding new marker and second is for displaying project info when user clicks on project boundary shape. I wanted to ask if those prompts will be used for this too?

Thanks

**Comment by FWAJL** [comment]
@damirius 

I think that @bsaiken will answer your question. 

@bsaiken: upload photos is not done yet. So I don't know if @damirius will be able to start Milestone C. Can you tell us what you would like to do?

Thank you.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
We are just about done developing a suite of bootstrap popup prompts, so if you need popups I would like you to adapt the popup structure we have, per the SOW.

Damarius - Jeremie had been working on the code to handle uploading and displaying documents, including photos, but has not been able to finish this yet as I have him assigned to other work.  Would you be interested in taking on some of the document handling work?  For your part, we could put a test photo in the database and all you would need to do, for Milestone C, is display it.  We could make this an add-on to the mapping work, or start a new eLance project.

**Comment by damirius** [comment]
@bsaiken 

I'm interested, but I would like to see specifications for that other project (or rather part of the project) so that I know what exactly needs to be done. 
Also I'm not perfectly clear on this part:
"For your part, we could put a test photo in the database and all you would need to do, for Milestone C, is display it."
I'm little confused about Milestone C there, since as far as I know we don't currently have image path field in the db tables for facility/project or locations. I see that in Milestone D it's specified that locations will have info window with photos in them, but before that only Milestone C have location info window shown in slides with little photo icon which I assumed that's used only for photo uploads for new markers. So there are no prompts which will require any photos before that. So to summarize, image upload for locations in Milestone C, displaying images for locations for Milestone D.

**Comment by bsaiken** [comment]
@damirius 
You are correct, I meant Milestone D.  You would need to be able to upload and display photos.  Photos are not part of Milestone C.  When I say "photo" here, I mean exclusively a photo image, taken with a smartphone or tablet, of a specific Location.  The purpose of the photo would be, for example, to help a Field Technician identify and find the Location.  I am not talking about generic "images" here, which could include icons, gylphicons, etc.

I will have some specifications for you in a little bit.  Since some of the groundwork has been done, I will need to review the code to see what is left to do.

**Comment by damirius** [comment]
@bsaiken 
I was mislead by info prompt shown on slide 13, since there's little camera icon in the lower right part of the window. Also, I understand that photos are the actual photos of the locations so it's all clear.

Thanks

**Comment by bsaiken** [comment]
@damirius 
I see.  That camera icon is inherent from the Google Maps interface, which I used to create the slides.  You could use it or ignore it if it does not serve our needs.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

There's a new commit for this milestone on feature_mapping branch. 
Please note few things:
We will probably need to remove circle shape, from boundary tool since we can't normal LatLng path from it. Tell me if that's posing some problems.
Adding new marker will not place it in the list since it's not actually saved in the db.
Editing existing marker with no LatLng data will add the appropriate marker based on "active" field and it will update it's image in the list too. Of course it isn't actually saved in the db just as new ones.

**Comment by bsaiken** [comment]
@damirius 
Remove the circle and the rectangle from the boundary and measuring tools.
Will you use some kind of "Add" button to save markers to the db?
I noticed you have the breadcrumb in the sidebar.  We don't need it since the page already has a breadcrumb.  
The sidebar is enormous - we can fix this, yes?

**Comment by damirius** [comment]
@bsaiken 
I'll remove the circle and rectangle shapes

The plan is that when the user clicks on the map and creates the marker, prompt box will show so that user can enter the name of the location and to click save so that marker get stored in the location table. If he closes the prompt box by clicking cancel, marker will not be saved and it will be removed from the map. I had already placed some info window to trigger on marker placement, but I removed it since I wanted to implement that new prompts for Milestone C.

I used slides as guidance for the design so I added current project name there, it isn't actually a breadcrumb, I can remove it in any case. Those arrows are used to hide/show the sidebar on click. I can reduce the width of course no problem, but I think it would be great if we could also keep those arrows (we can change them to something nicer) to hide it if we want, since even with smaller size it will take some precious space from the map and it could probably hide some markers.

**Comment by bsaiken** [comment]
@damirius 
That all sounds good.  We could even move the sidebar to a separate div because you are correct - covering up markers is a no-no.

**Comment by damirius** [comment]
@bsaiken 

Can you tell me if that's all for the function review so I can assign this back to me and finish up the changes?

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Sorry, I thought you were still working.  It is ready for code review.

**Comment by damirius** [comment]
@bsaiken

Sorry for misunderstanding, I wanted to ask you if there is anything else that needed to be done aside from that rectangle/circle shape removal and putting sidebar to separate div? Also project name should be removed right? I wanted to finish those things up so I can push the changes for function review again, before @FWAJL takes a look at code tomorrow.

**Comment by bsaiken** [comment]
@damirius  
It looks like there is just some formatting, which can be done later.

**Comment by damirius** [comment]
@bsaiken

I have already changed the code so I've pushed all the changes on feature_mapping branch. Map layout is divided into two columns, one for map-info sidebar and one for the actual map. I also removed shape/rectangle options from shape/ruler controls and I've removed "breadcrumb" from sidebar also. This will resolve the issue with covering up the markers without any need for hiding the sidebar. Also sidebar is also little less wide, I think it was 350px now it is 250px.

I would appreciate your feedback for these frontend changes. I had them already done, thought that you were still reviewing so I waited for more input regarding the frontend. Sorry again for taking up your time for these reviews.

Thanks

**Comment by bsaiken** [comment]
@damirius 
This is fine.  We can do the fine-tune formatting later - and that is not really your job.

**Comment by FWAJL** [comment]
@bsaiken 

I have a conflict in priorities: this issue is ready for code review as the popup milestones are ([issues to review in very high priority](https://github.com/FWAJL/FieldWorkAssistantMVC/issues?q=is%3Aopen+label%3A%22priority%3Avery+high%22+assignee%3AFWAJL+label%3A%22status%3A+code+review%22)). 

Can please downgrade the priorities where it applies so I know where to start first?

Thank  you.

**Comment by damirius** [comment]
@FWAJL

Is review done for this one?

**Comment by FWAJL** [comment]
@damirius 

Just writing it ;) Hang on :)

**Comment by FWAJL** [comment]
@damirius 

Only a couple remarks to take care of:
- There is a problem with facilities with no coordinates. The marker icon doesn’t display or is missing. See [this screenshot](https://docs.google.com/file/d/0B2j01q2xtCOtOTdISXBMZk1jeUU/edit?usp=drivesdk) for Facility 362. Can you look into it?
- Can you please use a CSS class instead of inline CSS? Add the class and its CSS in the app-theme.css.

Thank you.

**Comment by damirius** [comment]
@FWAJL 

Marker icon wasn't set in the controller, now it is. I was under the wrong impression that facilities must be set.
Also can you tell me which browser are you using since my sidebar is showing normally in firefox and chrome, with no overflow?

I've used js to add background-color for active controls and markers in the sidebar. If you mean that, I've changed it to addClass/removeClass and added few classes in the app-theme.css.

Thanks

**Comment by damirius** [comment]
@FWAJL

I made some tweaks to map-info sidebar in css. It should fix the issue with overflowing.

**Comment by FWAJL** [comment]
@damirius 

Yes, addClass / removeClass is a good solution to the css in the maps.js

Ok I'll look at it. Thank you

**Comment by damirius** [comment]
@FWAJL 

Just wanted to say that I'm using map_manager.js instead of maps.js, I just moved and renamed the file. Maps.js is still there but it isn't included anywhere. I'll probably remove it since we don't need it anymore. It isn't exactly service so I opted for classic manager file like others we use for locations/tasks/projects etc.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I just looked at the mapping UI.  There are still some formatting issues with the sidebar.  However, as long as everything functions correctly, please do not spend time refining the css.  I will likely want to play with the view myself until I can get it looking like I want.

In case you are curious, this is what I see.  But, again, no need to rush and fix this.

![screen shot 2015-02-25 at 5 57 48 pm](https://cloud.githubusercontent.com/assets/8228624/6384354/9d6cf9d6-bd18-11e4-939f-7967c1691a38.png)

**Comment by FWAJL** [comment]
@bsaiken 

Can I release this tomorrow?
Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
Please do.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
There are issues with this release.

1) Task markers are undefined.

![screen shot 2015-02-27 at 9 54 59 am](https://cloud.githubusercontent.com/assets/8228624/6416898/ddb639cc-be66-11e4-99ec-9751a3cbc846.png)

2) All Projects not displaying some icons and the sidebar is displaying duplicate entries.

![screen shot 2015-02-27 at 9 52 14 am](https://cloud.githubusercontent.com/assets/8228624/6416913/043f0402-be67-11e4-8c1c-9ce3c8a6c962.png)

**Comment by damirius** [comment]
@bsaiken

I would appreciate if you could send me your current sql dump, so I can test it with all that new stuff I see on those screenshots and see what's up.

Thanks

**Comment by bsaiken** [comment]
@damirius 
The Milestone B test was done on the live site.  You should be able to duplicate the bug.  Let me know if you can't.

**Comment by damirius** [comment]
@bsaiken

NoLatLng icon wasn't set by that controller, it works on other pages, we changed that in some of the previous commits on feature_mapping.

Also those aren't duplicate entries I believe. You can check facility names for each project and see that facilities have the same name for most of them. Some of them use EC as facility name others use Facility 490 as the name.
For example project 490 has facility with name Facility 490, but so do Project 490-2, Copy firevox 2 too.

Also like it was discussed on Milestone C issue, I've saved all those icons in the local directory and linked them from there, so that should fix loading times and some problems with images not showing because google's icons were unreachable.

**Comment by bsaiken** [comment]
@damirius 
Thanks - I get it now.
