### ISSUE TITLE
Mapping - Milestone C

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#522]

**Comment by FWAJL** [comment]
@damirius 

I'm splitting this issue into the 3 stages to make it easier to review your code later.

Please commit the code separately for each issue below:
Stage 1: https://github.com/FWAJL/FieldWorkAssistantMVC/issues/573
Stage 2: https://github.com/FWAJL/FieldWorkAssistantMVC/issues/574
Stage 3: https://github.com/FWAJL/FieldWorkAssistantMVC/issues/575

Thank you.

**Comment by damirius** [comment]
@FWAJL

Sorry, but it would be great if you could notice me of changes like this before, since Milestone C is done. I've finished it up and waited for the review of Milestone B.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Technically, according to the agreement, you should wait until a Milestone is approved before moving ahead with the next Milestone.  I understand, of course, that sometimes that is not practical from a coding perspective.  However, please adhere to this where possible.  
No harm done, though, and I am eager to see the new code.  If you push it to the feature_mapping branch I will look at it right away.  
Also, please tie up the loose ends in Jeremie's comments on Milestone B prior to finalizing Milestone C.
Thanks.
Brian

**Comment by damirius** [comment]
@bsaiken @FWAJL

I understand. I had to organize my time better since I finished almost everything by Friday if you don't count few changes to the sidebar positioning. I will wait from now on before milestone is fully reviewed.

Do you want me to include all changes from Milestone B (css reformat and broken inactive icon for facilities) together with Milestone C in the new push?

Thanks

**Comment by damirius** [comment]
@bsaiken @FWAJL 

New commit is up. 

Controls:
Ruler should be activated for all map pages.
Marker edit should be activated only for "All project's location" page
Boundary edit should be activated for all map pages except the first (All projects)

Marker edit control:
Click on it to activate it in the sidebar, map should become clickable. If map is clicked, user will be presented with a prompt. Prompt uses existing popup_prompt module. It checks for existing location name for the current project and it checks if the name is empty.
On clicking OK, it will save the location lat/lng together with name in the db. New row will be added with the location name and marker icon in the sidebar.
On clicking Cancel or just clicking outside of the prompt modal it will remove the marker from the map and nothing will be saved in the db.

Activate marker edit control and then click location with no coordinates (light blue icon). Click on the map, it will update the coordinates for that location. Icon in the sidebar for that location will be updated and location will not be clickable from now on in the sidebar.

All markers are draggable. Move any marker and it will update lat/lng info for that location in the db.

Boundary control:
On map load, boundary path is fetched. If there is boundary for the current project, map will use fitBoundary function to zoom and pan to boundary. If there is no boundary it will fallback to fit by markers.
Clicking on the boundary control will activate the boundary edit mode. Drawing controls will be shown in the upper part.
Clicking on polygon shape in the drawing controls will make the map drawable. When user finishes drawing the polygon, old polygon will be removed and new one will be saved in the facility table as the boundary.
If there is an existing boundary already, activating boundary control will enable the user to edit the path of that shape. Clicking between path nodes will create new ones and user can also drag existing ones. With each update to the path, facility boundary will be updated too.

Last minute tweaks for milestone B are implemented.

I'll have more info about code changes for the code review.

Thanks

**Comment by bsaiken** [comment]
@damirius 
I am still working on the review and I found a bug that is hampering my review process:
When I move Locations to "inactive" they are deleted.
If you can not easily re-create the problem, please let me know and I will give more details.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I have a more comprehensive review.
1) If there are no Locations, or none of the Locations have coordinates, the map center and zoom needs to be the Project coordinates.
2) The button to de-activate Locations is deleting the Locations.
3) Inactive Locations should be small_X, including Locations without coordinates in the sidebar.
4) When I add a Facility boundary, nothing is displayed and the center is set to 0,0.

**Comment by damirius** [comment]
@bsaiken @FWAJL  
1) OK, that will be changed to first fit the boundary if boundary is available, then to fit the markers boundary if there are more than 1 marker, then to center and zoom on 1 marker if there is only one location marker and in the end to center on facility marker.
2) I can't recreate that bug in the location list page. I had to use different controller action for editing my locations, but I haven't changed existing methods. I'll check it out to see if I can find what can be causing this problem.
3) I've used small_blue for inactive locations which is just a blue dot as specified: Location markers (inactive) : small_blue. I also don't think that locations without coordinates should have the same marker as inactive locations, if that is what you mean.
4) Google libraries aren't loading properly, I'll talk with @FWAJL since method for loading them was changed

**Comment by FWAJL** [comment]
@bsaiken @damirius 

4) The fix is pushed via #532.

**Comment by damirius** [comment]
@FWAJL

Regarding deactivating locations, I've found the problem. At first it looked OK, but locations were being deleted from the DB.
On line 175 of LocationHelper.php there is call for DeleteLocation function. Now we are sending the name of DAL which should do that. As far as I can see we are sending "TaskLocation" as the name of the DAL. So I assume that point of that was to remove task from location if location's active field was changed. 
DeleteLocation method in the helper just gets the Dal manager and runs delete method of the manager. Since TaskLocationDal class is just extending BaseManager but it isn't overwriting delete method, parent delete method is called. Since we are passing just the location object to it it will check for object's table here on line 114 of BaseManager.php: $this->GetTableName($object). Table name of the location object is, well, location table. So instead of deleting relation between task and location (task_location) it is deleting the location itself.

This issue isn't maybe the best place for conversation about this, if you wish we can create new issue or something like that.

Also thanks for that router fix.

**Comment by FWAJL** [comment]
@damirius 

Deleting a `task_location` deletes a link between the table `task` and the table `location` using respectively the `task_id` and the `location_id` of each. We store the pair in the table `task_location`, not in the table `location`.

So if you call `LocationHelper::DeleteLocation` with `Task_Location` as the DAL name, it'll delete the task_location item, not the location.

See `LocationHelper::UpdateLocations` for the example of deactivate/active one or several locations.

See `LocationHelper::UpdateTaskLocations` for the example of delete on or several task locations that represents a link between two tables.

In your case, you have two things to do:
- you need to update locations if you are deactivating them in the table `location`. You need to pass a `Location object` to the Dal.
- If you deactivate task location, you delete the link between task and location in the table `task_location`. You need to pass on a `Task_Location` object to the Dal.

Does it clarify your task?

**Comment by damirius** [comment]
@FWAJL 

I understand all that. 
I was actually talking about `LocationHelper::UpdateLocations` method. If you check line 175 you will see a call made to `self::DeleteLocation` with 'TaskLocation' beeing sent as `$dal_name` parameter.

As I said, this will not work since the object being sent as the third parameter is the `Location` object and TaskLocationDal manager is deleting the location instead of task_location.

Also my map project doesn't have the option of making locations inactive. I'm talking about existing feature on the 'location/listAll' page which I haven't worked on.

**Comment by FWAJL** [comment]
@damirius 

I see now. Good job spotting it. We'll wait for @bsaiken to decide who does this.
The issue #583 is created for the fix of the bug.

Thank you.

**Comment by bsaiken** [comment]
@damirius 
This is looking good.

Reminder that Task Location markers are red_circle.

**Comment by damirius** [comment]
@bsaiken

I'll copy it here from your eLance message as a reminder:
https://www.google.com/fusiontables/DataSource?docid=1BDnT5U1Spyaes0Nj3DXciJKa_tuu7CzNRXWdVA#map:id=3
Project markers (active)     : purple_stars
Project markers (inactive)    : wht_stars
Location markers (active)    : blu_circle
Location markers (inactive) : small_blue
Task Location Markers     : red_circle

So only one that was chosen by myself is that separate icon for locations with no coordinates. It is default shape, just most of the others, only without any shape inside it and in the light blue color.

Also as FWAJL mentioned before, task 4 is already done and merged with the branch when he fixed that issue with external javascript links.

**Comment by damirius** [comment]
@bsaiken
New version of feature_mapping branch is pushed.

I noticed that I had implemented some code for currentProjectLocations map which sets default coordinates to facility coordinates if there are no markers. I used that for task locations map too.
I've included those changes to LocationHelper which solve that bug with the location removal when making them inactive.

As far as the marker icons go, if you would like to see something different we can change that easily from the config where they are linked.

I'll talk more about code with @FWAJL when we get to code review part.

Thanks!

**Comment by FWAJL** [comment]
@damirius 

Don't forget to change the status label  and the Assignee. See Step 4 of [the worflow document](https://docs.google.com/document/d/1COa-OrxiAMfBzTmQfwsDU2xYbwZBWwRpbOxLzmWKvW0).

Thank you in advance.

**Comment by damirius** [comment]
@FWAJL

Forgot this time, sorry.

**Comment by FWAJL** [comment]
@damirius 

Not worries. It is a lot to learn in a short time and everyone works differently.
Thank you for your work so far :+1:

**Comment by bsaiken** [comment]
@damirius 
The only thing I see is that Task Locations are not red_circle.

*As far as the marker icons go, if you would like to see something different we can change that easily from the config where they are linked.*
I did not find the config file you are referring to.

**Comment by damirius** [comment]
@bsaiken 

This is the linked marker icon for task locations http://maps.google.com/mapfiles/kml/paddle/red-circle_maps.png
Config file is `appsettings.xml` under the Mapping section

**Comment by bsaiken** [comment]
@damirius 
I see why I was not finding it.  I was searching for red_circle (which is what I identified, above) but it is really red-circle.
I'm not sure I like having to go to google maps every time for a marker.  Is there a better alternative?

**Comment by damirius** [comment]
@bsaiken

If you go here: https://www.google.com/fusiontables/DataSource?docid=1BDnT5U1Spyaes0Nj3DXciJKa_tuu7CzNRXWdVA#map:id=3 and click on the marker that is set as our task location icon (it's in a 4th row in that bunch of default shaped markers on the right side) what does the popup says? For me it shows "Icon name: red_circle" in the first line.

I can save those that we use in some local directory and reference them from there.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

Ready to release tomorrow.

**Comment by bsaiken** [comment]
@FWAJL 
Since you are releasing tomorrow morning, I will wait for unit testing until then.
