### ISSUE TITLE
Task Lab Matrix UI

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#556]
![screen shot 2015-02-19 at 9 38 47 pm](https://cloud.githubusercontent.com/assets/8228624/6281505/e7409fec-b87f-11e4-8676-09eee39adbb4.png)

**Comment by bsaiken** [comment]
@gsouvik 
All I did was show the table.  You will need a new database table for this Issue: lab_analyte_location with location_id and lab_analyte_id.  There are other ways to do this.  When I programmed this is the first mockup for the site, I saved it as a data pair.  So these tow tables are the same:
lab_analyte_id

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've completed the Task Lab Matrix UI coding. The relationship data is saved in the table "lab_analyte_location". Steps to test:
1) Open the screen "Lab Matrix" under Task > Edit, it should be already populated with the pairings saved earlier.
2) If this is the first time the screen is opened, all the checkboxes are unchecked.
3) User may select the pairs and check the proper checkbox and click Save. The data is saved in backend and message is displayed.
4) Clicking on check/uncheck all, toggles all the checkboxes of the matrix.

While developing I noticed few things for which I would like to ask about:
1) I noticed another table "lab_sample_matrix" which is exactly same as the one which we used. I wonder if this table could have been used for this task. 
2) I would be starting with #557 next and was looking for the table and found "field_sample_matrix" which is identical as well, and may serve the purpose. 
Please let me know if I may use this existing table or a new table such as "field_analyte_location" needs to be created.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Yes, we had already prepared the tables you needed, but `field_analyte_location` is fine.  We can delete the other tables.
I will do the function review soon - having trouble pulling your code.  This happens from time to time and is usually temporary.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Looks great!  Thanks.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

Is it supposed to look like this?
![screen shot 2015-04-05 at 21 03 33](https://cloud.githubusercontent.com/assets/7524388/6998144/bc433d16-dbd6-11e4-9f83-42496552ed5c.png)

It looks like that my analyte names and the amount of them is messing up the UI.
We may need to think about a limit number of columns, set a width for the columns depending on a paging (5 by 5 analytes maybe horizontally). You will see below a live test I did to display the matrix better in my scenario. However, we don't want the display to break otherwise the PM can't really know where to click.
![screen shot 2015-04-05 at 21 05 27](https://cloud.githubusercontent.com/assets/7524388/6998168/977157ec-dbd7-11e4-8e35-7588bd4de8bb.png)

Other than that it is nicely server side. Good job @gsouvik :+1: 

@bsaiken : do you want me to release the code knowing about the UI issue?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
! see that you tested with so many analytes that the display wraps.  If you test with fewer analytes, it looks fine.  So, I'd like to release the code, but we will make a new Issue to handle too many analytes.

Shouldn't it be as easy as putting it in a scrollable div, and the div scrolls left-right as well as top-bottom?

**Comment by FWAJL** [comment]
@bsaiken 

Ok for releasing it.

Scrolling is an idea. @gsouvik could look into it in a new issue. 
I think paging in better because horizontal scrolling is not available for user using normal mouse for instance (only a trackpad or magic mouse can horizontal scroll).

**Comment by bsaiken** [comment]
@FWAJL 
I agree with you.  I will make a new issue to add pagination.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've assigned #815 to myself, shall start with that next. 
Thanks.

**Comment by bsaiken** [comment]
@gsouvik 
That's fine.  Please be sure to check the prioritization.  I have set #726 and #727 to high priority.

**Comment by gsouvik** [comment]
@bsaiken Alright, I'll start with either #726 or #727 before shifting to #815.

**Comment by bsaiken** [comment]
Same Issue as #557.
