### ISSUE TITLE
Task Field Matrix UI 

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#557]
See #556

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
So for this task should I use the existing table "field_sample_matrix" or create a new one.
Thanks.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Since you used `lab_analyte_location`, use `field_analyte_location`.   We want the table names to be consistent.
You can rename `field_sample_matrix` if you want, or create a new table.

**Comment by gsouvik** [comment]
@bsaiken 
Ok, also I shall update a new db script for renaming the table.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've complete the Task field matrix UI coding. The UI is very similar to #556.
Also this commit includes the db script for renaming the table `field_sample_matrix`.
Please review and let me know if this looks good.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Excellent - thanks.

**Comment by FWAJL** [comment]
@gsouvik 

Please check if there are analytes available before loading the view (just like it is done in issue #556). Otherwise, we have the following warning:

![screen shot 2015-04-05 at 21 32 58](https://cloud.githubusercontent.com/assets/7524388/6998272/2498a8a2-dbdb-11e4-898a-04be605f665a.png)


Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Souvik,
Would it be possible to hide the `Field Matrix` tab if there are no Locations and/or Field Analytes?
Same for `Lab Matrix` tab.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Yes, I think it is doable, let me try.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I've made the analyte matrix tabs dynamic, in the sense, that if for a particular task, the combination of  location and Field/Lab analyte is not available, the Matrix tabs are not shown.
Please review and let me know.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
I am getting a strange bug.  See if you can reproduce it.

![screen shot 2015-04-06 at 2 23 31 pm](https://cloud.githubusercontent.com/assets/8228624/7012820/cbc7e0a6-dc68-11e4-87e8-18977f3cb9b8.png)

**Comment by gsouvik** [comment]
@bsaiken 
The issue seems to be coming from `LocationHelper.php`, which I haven't modified recently. I too noticed this issue when I pulled yesterday, but on a different page. I fixed it by running the db script `2014-04-01.sql` on my local. Please run that script and let me know if the error messages still exists.
Thanks.

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
Jeremie,
I downloaded the live database prior to performing my function review, so I don't think my version of the database is behind.  Please advise.

**Comment by FWAJL** [comment]
@bsaiken 

The updates are not run on the live database yet. I will later today.

@gsouvik 

Where is the 2014-04-01.sql script? I don't see it on any branch... or is it 2015-04-02.sql script?

**Comment by gsouvik** [comment]
@FWAJL 
https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_devsupport/Database/Scripts/Updates/2014-04-01.sql

**Comment by FWAJL** [comment]
@gsouvik : thank you :+1: 

@bsaiken : please run this on your local DB or wait tonight to retrieve the Live DB:

```
-- Update for 2015-04-01
-- > Update to the table task_location
USE baiken_fwm_1;
ALTER TABLE `task_location`
ADD COLUMN `task_location_id` INT(11) NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (`task_location_id`);
```

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
We should have put this through function review before releasing.
The result is not what we need.
When I first open the Task, the lab matrix tab is visible.  Clicking it, I get this:
![screen shot 2015-04-08 at 2 11 47 pm](https://cloud.githubusercontent.com/assets/8228624/7055613/9c21516a-ddf9-11e4-9e3f-c984d4a55388.png)

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

Is the problem the fact that the analytes are not present and it is not saying what to do?
Thank you.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
On my branch `dev_support`, when no task specific analytes and locations were available, the tabs were NOT visible.  This was from my last commit id `f0cc4fb`. I'll test the current status after so many merges and update you what it looks like at present and why it might be looking like that.
Thank you.

**Comment by FWAJL** [comment]
@gsouvik @bsaiken 

I see on the dev branch and the devsupport branch that the Matrix tabs are displayed when on the page `/task/showForm?mode=edit&task_id=id`. But if you navigate to any other tab, they are hidden. Is it maybe the issue Brian is having? If so, the bug is really part of #763.

Let us know

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I just test on the most updated code on my branch `dev_support`. It seems to be working correctly.

This is the screenshot when the lab analytes are assigned to the Task. The Lab matrix tab is visible
![screen shot 2015-04-09 at 9 49 05 am](https://cloud.githubusercontent.com/assets/2292482/7060429/763fd9d0-de9e-11e4-918c-e13f32701961.png)

And then when I removed the lab analytes and go to the edit task tab i.e. the first tab, the lab matrix tab is not visible any more.
![screen shot 2015-04-09 at 9 50 06 am](https://cloud.githubusercontent.com/assets/2292482/7060445/a25540be-de9e-11e4-93a0-08232548a607.png)

This example is only using Lab Analytes, but I tried with Field Analytes too, and it worked. Even I logged out completely and then logged back in to test and it worked. Am I missing any step where the bug is showing up?

**Comment by bsaiken** [comment]
@gsouvik 
Please follow these steps to see the bug:
Navigate to http://dev.fieldworkmanager.com/login
Make sure you are logged out.
Login as test:test
Click Task > List All
Choose the Project: EX-TX
right click on `Test Task` >> edit
You should see this:
![screen shot 2015-04-08 at 9 55 58 pm](https://cloud.githubusercontent.com/assets/8228624/7060651/18547042-de3a-11e4-9297-52525f443a63.png)
Both the `Field Matrix` and `Lab Matrix` tabs should be hidden, but they are not.  If you click on the `Field Matrix` tab, you see this:
![screen shot 2015-04-08 at 9 57 29 pm](https://cloud.githubusercontent.com/assets/8228624/7060668/46dd5154-de3a-11e4-8304-dbb7e9dcb19b.png)
It shows the contents of the Field Matrix, and there is nothing wrong with having an empty matrix, but the tab itself is missing.

**Comment by gsouvik** [comment]
@bsaiken 
Ok, I understand the issue now, as @FWAJL suspected it is more of an issue which would have resolved as part of #763. But I'll patch it here on this issue only. Then shall proceed with #763 separately.
Thanks for explaining the steps, helped me figure out the problem.

**Comment by bsaiken** [comment]
@gsouvik 
Yes, that is why I created Issue #763, because I think if you resolve Issue 763, this Issue can be resolved at the same time.

**Comment by gsouvik** [comment]
@bsaiken 
I've changed the code to fix the issues we were having regarding the Analyte matrix tabs when the checkboxes on the task edit page were checked.
As discussed, the behavior of the matrix and other tabs with the checkboxes would be completely looked into in issue #763.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
Yes - thanks.
