### ISSUE TITLE
Use arrows for activate and de-activate buttons

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#565]
Change the "move to active" and inactive list buttons to be arrows.

**Comment by bsaiken** [comment]
@FWAJL 
Since all the buttons are the same, I prepared a module "promote_buttons" to apply to every page.

As I was doing this work several questions came up:
1) It appears the module Service -> listAll is deprecated.  It's function is taken by manageServices.  This means we have an inconsistency in the way the modules are constructed.  Shouldn't this be fixed?  Why can't this follow the same pattern?

2) I was able to apply the module to pages where the modules are defined this way:
    
$modules = $this->app()->router()->selectedRoute()->phpModules();
    $this->page->addVar(
        \Applications\PMTool\Resources\Enums\ViewVariablesKeys::promote_buttons, $modules[\Applications\PMTool\Resources\Enums\PhpModuleKeys::promote_buttons]);

However, modules are also defined this way:

 //form modules
    $this->page->addVar(
            \Applications\PMTool\Resources\Enums\ViewVariablesKeys::form_modules, $this->app()->router()->selectedRoute()->phpModules());
and then the module is called in the view like this:
          <?php require $form_modules[Applications\PMTool\Resources\Enums\ViewVariablesKeys::categorized_list_left]; ?> 

Is this an inconsistency in our coding - shouldn't they all be done the same way?

**Comment by FWAJL** [comment]
@bsaiken 

1) You created this ProjectService controller and the manageServices and yes, it could have been done in the ServiceController, ListAll method. At the time, I was surely busy with something and I didn't ask why you did this. Anyway, it is working and yes, you remove the ListAll module under the Service views folder.

2) Prefer using the second option. You update any where you find the first implementation making sure you update both controller method AND the view. It can break the site otherwise.

Thank you.

**Comment by FWAJL** [comment]
@bsaiken 

Incorporated into the releaase 1.6.7
