### ISSUE TITLE
Deactivate a location deletes it

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#583]
@bsaiken 

As @damirius has found out while doing issue #522, when we deactivate a location, we delete it also.

The reason is that when we deactivate a location, we need to delete the related ***task_location*** if there is any.

TODO:
- After the edit of the location (either activate/deactivate), we need to update the sessionProject (or at least make it is up-to-date).
- Delete the task_location (only when deactivate a location).

**Comment by damirius** [comment]
@FWAJL @bsaiken

Can someone tell me which branch do we want to use for this one?

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I made a new branch for you: feature_dd.  Use this for all hourly work.
You can use the same login: mapping ; mapping
https://github.com/FWAJL/FieldWorkAssistantMVC/tree/feature_dd

**Comment by bsaiken** [comment]
@damirius 
Normally, I will set everything up.

**Comment by damirius** [comment]
@bsaiken

Thanks, I have it done on my local branch already. I'll migrate the code needed for this and let you know when it's pushed here.

**Comment by damirius** [comment]
@bsaiken

I've added modified code on that branch and pushed it here. Can you tell me from where you branched this feature_dd branch? I noticed that "activate/deactivate" button is displayed as an arrow. Just asking since I don't know how old that code is there.

**Comment by bsaiken** [comment]
@damirius 
I JUST CREATED THE BRANCH FROM THE DEV branch.  The code you have is the most up to date there is.
Lots of changes going in with the site, which is why you need to do frequent pulls.

**Comment by bsaiken** [comment]
@damirius 
Maybe I was premature to have you work on a separate branch, since this code is needed for the mapping UI.  It would probably work best if you copied the new LocationHelper to your local feature_mapping branch.

**Comment by damirius** [comment]
@bsaiken

OK, not a problem. It will be pushed together with other changes that you asked for in the function review for mapping Milestone C.
I would appreciate your input on marker icon changes for that. When that is done I'll have the code ready and pushed for the next round of reviews.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I found a bug in the Task Locations UI.  I think it was cased by work on this Issue.  
Navigate here:
Task > List All
Right click a task and select "Edit" (or "View Info").
Click on Locations tab.
Try promoting one Location from "Project Locations" to "Task Locations".  Does not work.
The error does not occur for promoting multiple Project Locations.

![screen shot 2015-02-26 at 1 15 29 pm](https://cloud.githubusercontent.com/assets/8228624/6400967/fc9df896-bdb9-11e4-87cd-b7883362e58d.png)

**Comment by damirius** [comment]
@FWAJL

Hey, can I get your input on this since I can't recreate the bug? If you could try it out on feature_mapping branch just to see if you are getting same error when adding project locations to task locations.

**Comment by FWAJL** [comment]
@damirius 

Can't check it until Monday.
However, I can try to point you in the right directions:
- Have a NetBeans or your IDE debugger running
- Set a breakpoint at [line 11 of the TaskLocationController](https://github.com/FWAJL/FieldWorkAssistantMVC/blob/feature_popup/Applications/PMTool/Controllers/TaskLocationController.php#L11). Step into the `LocationHelper ::UpdateTaskLocations` and check why `$result["rows_affected"] === count($result["location_ids"]` is FALSE on the return of the method.

BTW, if you have no debugging setup, you can use the `DegubHelper::LogAsHtmlComment($aString)` to log PHP data.

I hope this will help you.

**Comment by damirius** [comment]
@FWAJL 

Well good thing is that it doesn't have anything to do with that other modification on `UpdateLocations` method. Since we are using `UpdateTaskLocations` for this. Well, now when I think about it, it's not really a good thing, it would probably be better if it had something to do with our last problem :)

In any case, thanks for the tips.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I just De-activated a technician from the Task Technicians tab and the technician was deleted.
It only happened the first attempt, but still a fatal flaw.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

On http://dev.fieldworkmanager.com/, I have added "Joe2" to the task technician of Project 490 and removed it from the task technicians. It didn't delete the technician but just the link. I have checked the database after the action to be sure and re-logged in.


Another point is that it will not remove the link between technician and task technicians if the technician is deleted. You would have to logout/login to have the data refreshed. 
Like locations, we need to update the session and delete the link task technician when a technician is deleted or deactivated.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

@FWAJL Aren't all relation tables set with `on delete cascade` foreign keys so we don't have to worry about that?

**Comment by FWAJL** [comment]
@damirius 

You are right actually. Sorry for the mistake in my statement. I'll remove it. What you say is true.

However, it only works on delete action, not update.

**Comment by damirius** [comment]
@FWAJL

Yea. Actual problem is with session updates like you said and "active" field updates. Deactivating locations is no problem currently I think. There is a small bug with technicians and their relation to tasks. It's a problem with removing relations between technicians and tasks on deactivation of technicians, similar to locations.

The thing is if you deactivate technician from technician/listAll page and that technician is currently linked to some task it will still show under task/technician list. So quite similar to task/locations problem. 
When you remove that link between technician and the task there, technician will not show in the technicians list on the right side. Big thing to note here is that it doesn't actually delete technician, it just removes it from the task and the reason why it isn't showing on the right side is that "Available Technicians" list isn't showing inactive technicians.

**Comment by damirius** [comment]
@FWAJL @bsaiken 

New commit for this bug is on feature_mapping, since we agreed to push fixes for these bugs on this branch.

Recreating the bug on older versions of the branch or any other branch:
Set some project at the current project
Go to Technicians->Add, add new Technician for testing leave it active like it is set by default
Go to Tasks->List All, right click some task to edit it
On Technicians tab add new Technician from "Available Technicians" (those that are active for the project)
Go back to Technicians->List All and select technician that you've added to the task and deactivate it
Go back to Tasks->Edit task->Technician tab, you will still see technician under "Technicians for this task" list but it should be removed from there
In the new version there should be linked inactive technicians, they are automatically removed from tasks when they are set to inactive.

Same thing goes for locations

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I tested on the live site and do not get the bug.
If this is fixed, please close Issue.
