### ISSUE TITLE
Implement autocomplete on Lab Analytes (uploadList)

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#586]
The Lab Analytes autocomplete list will come from the table "master_lab_analyte".  
Issue #584 must be completed first.

**Comment by FWAJL** [comment]
@bsaiken 

Why a new table? Is common_lab_analyte not enough?

**Comment by bsaiken** [comment]
@FWAJL 
common_lab is not enough.

**Comment by FWAJL** [comment]
@bsaiken

Please describe it as much as possible.

Creating a new table, especially when it's a copy of another one very
similar is maybe not the solution.

Thank you.

--
Jérémie Litzler

**Comment by bsaiken** [comment]
That is the correct solution in this case.

**Comment by FWAJL** [comment]
@bsaiken 

Can you please still describe the use of these master_lab_analyte? 

I want to understand why it is the correct solution in this case.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
The common analyte list is a brief list of analytes that are most commonly used in my field.  
I added this feature as a convenience.  It is not absolutely necessary since the user could simply enter any analyte name of their choosing.  Giving the user this options will reduce spelling errors and, for field analytes, provide an example of the appropriate syntax (which includes the units).

The master_lab_analytes list is very different.  There are may hundreds of possible lab analytes - way too many to conveniently display in a common analytes list.  Even though this list is long, it is not exhaustive and I could copy lists from existing websites.  I have actually done this is prior database versions.  This list will contain all of the same lab analytes as the common_lab_analytes list.

I envision that as the site grows, I would add to both of these lists, as appropriate.  I might even remove items from the common lists, if no-one is using them (of course, I would have to track that).

The two convenience features are complimentary.

**Comment by FWAJL** [comment]
@bsaiken 

I understand now.

The common list can be part or the whole of the master list. Now it makes sense.

Thank you.

**Comment by FWAJL** [comment]
@bsaiken @gsouvik 

I have code available to speed up the process. I will share it soon.

**Comment by bsaiken** [comment]
@FWAJL  @gsouvik 
This applies to Issue #585 as well.

**Comment by bsaiken** [comment]
@FWAJL 
Isn't Issue #142 now deprecated with #585 and #586?

**Comment by FWAJL** [comment]
@bsaiken 

Yes, Issue #142 is not needed anymore.

BTW, the autocomplete from Xerox isn't suited for our use. Therefore, Souvik can use the jQuery Autocomplete to perform the task at hand. I think there're enough examples to develop it.

Thank you.

**Comment by FWAJL** [comment]
@bsaiken 

Is this still in "more info required"?

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
I just wanted to confirm, this is for the screens at `labanalyte/uploadList` and `analyte/uploadList`, right? Also the table `master_lab_analyte` doesn't have data in it on my local. Should I just enter some test data and test? Also would like to confirm, the auto complete should appear on the left hand textarea as the user starts typing? Pressing enter and switching to a new line would reset the auto-complete list and start over for the new line of text the user is typing.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Yes to all questions.

**Comment by gsouvik** [comment]
@bsaiken 
The auto complete feature for the lab analyte upload screen is done as per the questions I asked earlier.
It took little more time as I initially expected due to following reasons:

1) The DAO/DAL was not there for the mast_lab_analytes, I've added those into the codebase.
2) The jquery auto-complete widget automatically positions itself at the bottom of the element with which it is initialized with. But in our case it was a textarea and the position of list was getting set at the very bottom, making it unusable. This needed a bit of code experiments. 
3) Moreover in our case it had to be dynamic, each line the user types in and presses enter, the list should move down accordingly, and move up if the user deleted few lines of text. Did some coding and it works as intended. Here's some screenshots:

![screen shot 2015-05-31 at 4 57 01 pm](https://cloud.githubusercontent.com/assets/2292482/7901770/41c288c8-07b7-11e5-8411-5eab79e0c08f.png)

![screen shot 2015-05-31 at 4 57 25 pm](https://cloud.githubusercontent.com/assets/2292482/7901774/4946f296-07b7-11e5-91df-5654fd6da901.png)

4) Finally the autocomplete had to be modified to work on a multi line textarea, yet should just consider the last line of text in order to show the suggestion list.

**Comment by bsaiken** [comment]
@gsouvik 
It's not working for me.  Where are you getting the list source for the autocomplete?

**Comment by gsouvik** [comment]
@bsaiken 
As described in this thread, data should come from table "master_lab_analyte". I added some test data into it and tested. Let me know if you need the test records I inserted in that table.
Also the code is pushed to feature_devsupport branch.

**Comment by bsaiken** [comment]
@gsouvik 
Common analytes are listed on the right side, but in your example, the autocomplete options are not on the list.  Did you create a new table, `master_analytes`?

**Comment by gsouvik** [comment]
As @bsaiken said on 27th Feb
> The Lab Analytes autocomplete list will come from the table "master_lab_analyte".

The table `master_lab_analyte` was already available in my local database, I just created the DAO/DAL to use with it. 

I asked on 30th May
> Also the table master_lab_analyte doesn't have data in it on my local. Should I just enter some test data and test?

So I just entered some test data in that table and that is where the auto complete list is generated from. I've already sent you the data on eLance. 

So to test this, you just have to import that data into the `master_lab_analyte` on your local db. Then start typing on the left hand textarea of `labanalyte/uploadList` and `analyte/uploadList` and you should see the autocomplete suggestions.

**Comment by bsaiken** [comment]
@gsouvik @FWAJL 
That's it.  The table was not on my local machine for some reason.
Jeremie, make sure that table is included in the database reset.
