### ISSUE TITLE
Mapping updates

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#654]
* Make the selected Project marker the current Project
* In the Location Info window, for "View photos", and the number of photos to the string, e.g. "View photos(2)", if it is zero, do not add the string.
* Add photos interface to Task Locations info windows
* Include the ability to remove photos.

**Comment by damirius** [comment]
@bsaiken

Few small questions regarding this issue.
I should make the project active when user opens info window for that project (clicking on the marker in sidebar/map)?
Ability to remove photos should be added to both Location Info windows and to Task Location Info windows, plus as the part of the other issue to the location/showForm page?

**Comment by FWAJL** [comment]
@damirius 

Please wait that the current merge on mapping branch is complete before committing new code.

Thank you.

**Comment by bsaiken** [comment]
@FWAJL @damirius 

This Issue is "on hold" and unassigned, so I think we are just answering a few questions here.
Q1.  Don't make the Project "active" when the info window opens, but make that the current Project.  Making a project active (or inactive) will create behaviors that have not been developed yet.  I need to alert the user what the consequences are when making a Project active or inactive.
Q2. Any Location info window should include the ability to add and delete photos.  Let me create the Issue for the location/showForm page and I will explain the details there.

BTW - with respect to your other comment, I don't want a popup box alerting the user there are no photos, I want it done as stated above.  

Do not add any popup boxes unless I request it.  If you think one is needed, I welcome you to point this out, and I will decide.

**Comment by damirius** [comment]
@bsaiken

q1. Sorry I've used the word "active" I've meant make it the "current session project", not active/inactive.

Also that "no photo" popup was there with the first commit, just tooltip didn't work because of the merge. I'll remove it with this update and add the photo counter next to the string in which case if there are no photos there will be no link.

Also I'm still not working on it so there will be no commits for now.

Thank you for your input

**Comment by damirius** [comment]
@bsaiken

Since I'll have to start working on this soon I'll need more info about this.
"Add photos interface to Task Locations info windows"
We want this on every location on task locations map? So on both Project Locations and on Project Task Locations? Also when adding new photos to Task Locations do we add them to the Task or to the Location?

"Include the ability to remove photos."
I don't know where should I add div#documents there since already we have little space in the window. I would appreciate if you could do some screenshot mockup of the infowindow with all new stuff that we need.

**Comment by bsaiken** [comment]
@damirius 
I will answer question 2 on the appropriate Issue.
As far as Task Locations: include the photo interface that we have at `/map/currentProjectLocations` for the popup windows at `/map/currentProjectLocations`.
Photos are always related to Locations (there is no photo - Location relationship).
Brian

**Comment by damirius** [comment]
@bsaiken

* *Make the selected Project marker the current Project*
Go to Map->All Projects, clicking on markers on map or sidebar will open up the Project Info window as usual but it will also set the current project to the parent project of that facility.

* *In the Location Info window, for "View photos", and the number of photos to the string, e.g. "View photos(2)", if it is zero, do not add the string.*
Added view photos counter for Locations with photos and hid the "view photos" link for Locations without them.
* *Add photos interface to Task Locations info windows*
Upload module is added to the Location Info window on task map (Map->Task Locations), it functions exactly the same as upload box on Map->All project's locations.

**Comment by bsaiken** [comment]
@damirius 
When I upload a photo it asks me for a caption, but the caption does not display anywhere as far as I can tell.   Am I missing it?

**Comment by damirius** [comment]
@bsaiken

It should be the same for all lightbox images, when you click on 'view photos' picture should be displayed and 'title/caption' is shown in the lower left corner below the picture along with the number of the picture in the "gallery" (image x of x)

**Comment by bsaiken** [comment]
@damirius 
Please show me a screen shot of the live site.  As far a I can tell, the file name is being stored in the caption field even if I enter a document title.

**Comment by damirius** [comment]
@bsaiken

![lightboxss](https://cloud.githubusercontent.com/assets/1443969/6850698/fad44bbe-d3da-11e4-8b9f-943759bf6ae3.png)

Here it is screenshot of the open lightbox picture. You can check it out also on dev.fieldworkmanager.com. Login as mapping user select Tempe doggie dispensers project go to All Project's location and click on Tempe Beach Park location.
Only thing to note is that you need to add title before uploading the image, so maybe that was the problem?

**Comment by bsaiken** [comment]
@damirius 
I put a video demonstration on eLance - ignore it.  I see now that the user needs to type in the title prior to clicking the `class="dz-default dz-message"` div or the Title value is not saved.  If that is the case, and this is not fixable, we will need something, an alert box perhaps, checking to see if the title has been entered prior to enabling the photo upload, or a tooltip after the "Title" label.  This is too easy to overlook.  And, once the photo is uploaded, there is no way to modify the caption.  
Also, there is no way to delete any photos.

**Comment by damirius** [comment]
@bsaiken

Yea tooltip or something like that could be useful.
I've asked about deleting photos here:
"Include the ability to remove photos."
I don't know where should I add div#documents there since already we have little space in the window. I would appreciate if you could do some screenshot mockup of the infowindow with all new stuff that we need.

Maybe I misunderstood something, but I believe that you said that you'll answer that question on the appropriate Issue.

**Comment by bsaiken** [comment]
@damirius 
OK - I will create two new Issues to deal with these items. 
Just to be clear, and I correct that you can't modify the code to save the Title entry any time prior to clicking the "Upload" button?

**Comment by damirius** [comment]
@bsaiken

Since the title is saved in the same table as the file name and other stuff, we have to save it in the same time. So yes, we need to have title before uploading.
