### ISSUE TITLE
Display Location photos on /location/showForm

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#670]

**Comment by damirius** [comment]
@bsaiken

Added upload and removal of photos on Location form.
You can check it out on feature_damir branch.
Select the project, go to Locations -> List All -> right click location -> edit.
Upload box should be always visible. Existing photos should be displayed as columns width 4 (.col-lg-4). Functionality is similar to technician file upload, so not much to talk about here. One exception is that uploading new photos shouldn't replace old ones since we can have more than one here.
As far as the design goes, if you want different look it would be great if you could specify what you want to see changed.
If you want to change something yourself in CSS, you can open up `app-theme.css` and go to the bottom of the file under `FILE MODULES` section where you can find classes for `.remove-image`, that's that small 'x' button, `.document-block` is div wrapper for both image and 'x' button and `#document-upload` is upload box form.

**Comment by bsaiken** [comment]
@damirius 
I am not seeing photos displayed in any interface.  It may take a little time to do some more thorough function testing to see if I can give you more information. So far, I have only tested Firefox.

**Comment by damirius** [comment]
@bsaiken

I've tested it in firefox and chrome. There can be lot of reasons why it doesn't work. I hope you updated your database with changes for `document` table. I'll need your `/file/load` ajax call response so I can see what's wrong.

**Comment by bsaiken** [comment]
@damirius 
There have been a lot of database updates.  I just wiped my local database and used the database on the live site.  Still not working.  Docs are being uploaded, but no entries into the `document` table.

Is this the correct table structure?  

![screen shot 2015-03-19 at 4 06 05 pm](https://cloud.githubusercontent.com/assets/8228624/6743025/32b7b450-ce52-11e4-9031-a1bdf94a4efa.png)

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I found the database update.  I was behind...
