### ISSUE TITLE
Active Task - Discussion Thread

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#728]
Part 5 of Issue #404.

Prepare Discussion Thread tab contents.

![screen shot 2015-03-20 at 11 22 15 am](https://cloud.githubusercontent.com/assets/8228624/6758155/6f24d5de-cef3-11e4-8ec1-78e8fd14a915.png)

![screen shot 2015-03-20 at 11 22 27 am](https://cloud.githubusercontent.com/assets/8228624/6758161/77d3ac3c-cef3-11e4-85e5-6201b9c6f029.png)

![screen shot 2015-03-20 at 11 22 30 am](https://cloud.githubusercontent.com/assets/8228624/6758165/7fb24abc-cef3-11e4-9c8c-baec26ea4eeb.png)

The right hand column will show the list of Service Providers and Technicians. The Service Providers and Technicians are selectable.

The Service Providers for the Task are identified where task.task_id = task_service.task_id and task.task_id is the selected task.

The Technicians for the Task are identified where task.task_id = task_techncian.task_id and task.task_id is the selected task.

Selecting one of the right hand side options opens the discussion thread (left hand side) and will set a session variable ($currentDiscussion) that will be used to control the discussion.

Use a left arrow in the center column to select (“promote_buttons.php” module).

After selection, The breadcrumb in the header updates with the selected Technician or Service Provider.

There will be center column buttons to “Send” the new message and “Attach” files. Use the “task_buttons.php” module as a template for the buttons.

Implementation of the Discussion thread will be a separate SOW.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
#404 has other parts but the priority of those are not set to "very high" with the exception of this task. So do you wish me to start with this one next?

I have few questions on this task:
1) What happens when I select a service provider and a technician at the same time and then click the middle column "left" arrow. Do I have to make the selection mutually exclusive. 
2) What would be on the left side as a part of this task? Do I just have to show a textarea?
3) Will the "send" button functionality be included in this task? If yes, how should the attachment process work. Also after sending what should happen, do I need to record this in a database or update a session variable.

Thank you.

**Comment by bsaiken** [comment]
@gsouvik 
Issue #404 was the originating Issue.  There is really nothing to work on - we keep it for the communication history.
I set Issue #728 to "Very High" because I need it done first.
Only one conversation can occur at a time, so selections are mutually exclusive.
You do not need to put anything in the left side Except a placeholder.  The work to enable this tab is a separate SOW.
Put the "Send" and "Attach" buttons as placeholders.  No functionality.  That will be a separate Issue.

**Comment by gsouvik** [comment]
@bsaiken 
I've done the Active task discussion thread UI as per the discussion on this issue. I've used a basic session variable to assign the user with whom the communication is being started. Based on that session variable the UI is updated accordingly.
Please review and let me know your feedback.

Thank You

**Comment by bsaiken** [comment]
@FWAJL @gsouvik 
This looks great.
Jeremie, please do the code review and release ASAP as this is the last thing I need in order to send out the Discussion thread SOW.  Priority over all other Issues.
