### ISSUE TITLE
Make the first listed Active Project the initial current Project.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#734]
As we have it now, the $currentProject is only set automatically if there is only one active Project.  I don't like this solution.  I want a default $currentProject set when the user first logs in.  We already have a method to cover the condition where there are no active Projects.

**Comment by FWAJL** [comment]
@bsaiken 
Let's add a column `project_is_default` to the table `project` to define the default project for a given PM. 
We will need to set:
- either a database constraint to prevent multiple projects having the `project_is_default` set at the same time
- or do this logic in the code and having a prompt box that invite the PM to change the default project if a project is already set as default.

Also, is a checkbox ok with you to set a project as default?

Thank you.

**Comment by bsaiken** [comment]
@FWAJL 
No checkbox.  I want some way for there to be a Project set every time they log in.  Eventually, we would want to use the last Project they were viewing - generally when users log off, for any reason, that's where they expect to go back to.

**Comment by FWAJL** [comment]
@bsaiken 

Ok so we need to set `project_is_default` every time a project a selected. That's easy because we have a controller method that takes of that. We can add the bit to set `project_is_default` to true (or 1 since it will be a tinyint type).

Is that all correct?

**Comment by bsaiken** [comment]
@FWAJL 
That seems like a good approach.

**Comment by FWAJL** [comment]
TODO:

- add a column `project_is_default` to `project` table
- in `ProjectController`, method `executeSetCurrentProject`, update the project to be set as current to have the `project_is_default` property set to 1.
- when logging in, set the current project automatically to the one that `project_is_default` set to 1 (See `SetCurrentProjectIfPmHasOnlyOneAndReturnProjects` in `ProjectHelper`).

**Comment by damirius** [comment]
@bsaiken @FWAJL 

**RUN db update script 2015-04-23.sql FIRST**

Go to Projects->List All page, right click on some project-> Select (as current Project)
Logout
Log back in, you will see that same project is still selected as the current

On the first run all projects have their field set to 0, so first project from the list will be selected, we used this method till now.
When current project is changed from the list, all projects will have their `project_is_default` fields set to 0 so that we don't have multiple current projects in the db.
Keep in mind that clicking edit on the project for example will set him as the current, but it will not set him as the default one when the user logs back in. Setting project as the default is only possible by rightclicking the project name in the list and selecting 'Select (as current Project)' from the context menu.
