### ISSUE TITLE
Role management - Step 1 - Retrieve and store the role(s)

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#747]
Retrieve the `role` attribute on the route element in `routes.xml` to store it as an array of roles in the `Route` object. 

After thinking about it, it'll be easier to create a new route (and its controller method) for the FT interface than trying to include PM and FT logic in the same controller method (same route). 

So forget about the role attribute on php_modules.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
Continuing the discussion from Issue #421.  

We have been discussing this Issue under #421, which invites misunderstanding.  This Issue, and Issue #748, are prerequisites for Issue #421.  These are also per-requisites for Issue is #640.

Issue #640 is more pressing, so I have changed the priority to "very high".  Issue #421 has been put on hold for the moment.

I do want Damir to proceed.  However, before you do, Damir, I want to make sure we all understand the approach and that we all agree this is the most efficient way to proceed.  We will save time in the long run if we step back for a minute and re-examine the desired outcome, with a clearer understanding of what is required, and what can be put off until later. 

As I was writing my most recent comments on Issue #640 the requirements became clearer to me, and I hope now to everyone else.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I can start working on this whenever we sort out what we have on Issue #640. I mean when we sort out how do we want to proceed since we started talking there about most of these things.

**Comment by WebDevJL** [comment]
@bsaiken @damirius 

This task (issue #747) is only about storing the role(s) in each Route object. 

Each Route object is then added to the list of routes. 
It is built at the start and finish the application. 

Planned to have a route with multiple roles. This is to plan for the future or in case a route is viewable the y more than one role. This doesn't had more work normally. Tell me otherwise. 

That's all. The step 2 will take care of how to filter the routes based on the user. That's the interesting one! 

Let me know if it's not clear.

**Comment by damirius** [comment]
@FWAJL @bsaiken

Totally clear, I'll push that commit now. It's only few lines of code in the `Route` class, since like you said we are just storing them for now and in the next Issue we will implement actual auth checks for them.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

This was a rather small commit, it just reads the role attribute from the routes.xml and store it in the route objects.

Do you want me to set this for function review or code review? Since this doesn't have anything to do with frontend, don't want to break our workflow so wanted to ask first.

**Comment by bsaiken** [comment]
@damirius 
I am starting a function review right now, and I need to do a full unit test of your branch and the live site.  So I'll take it from here.  :+1:

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I just completed a function review and unit test of the feature_damir branch.  I found no issues.

Damir, for future reference.  I do unit testing weekly using a spreadsheet: 
https://docs.google.com/spreadsheets/d/19pvUh4dv2spQyTybsQHOSReDNdapnNrVkDBoDgLpyZE/edit#gid=0
If you are working on your branch, and you need something more than a simple function review, you can identify items from this list that need testing.  The list is dynamic and changes as the site develops.  You can request an item be added, too.
