### ISSUE TITLE
Role Management -  Step 2 - Filter the routes list for a user

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#748]
Filter the routes list for the user logging in to contains only the routes he can view. 

Include a fallback route so that the user sees a message when he tries to access a page he can't view (this will be useful to find bugs in development)

**Comment by damirius** [comment]
@FWAJL @bsaiken 

Few questions about this. Since we have to restrict the access to specific roles now, we need to hide the route links in the left menu also. Now there are few ways to do this, just wanted to ask you about your input on this. We can add role attribute to entries in `menus.xml` and read it from `LeftMenu` builder class. That's not the best way to do it since we have to add the roles in two files instead of one.
Other solution would be to read the set up roles for each routes through `$app` property somehow and then we can match `url` attribute of routes to `href` attribute of menus and try to check if we need to show it or not.

**Comment by FWAJL** [comment]
@damirius

You are right and I'm just about to write you the task list for this. Hang on and I will list you what to do.

Thank you for the quality work you do :+1:

**Comment by FWAJL** [comment]
@damirius @bsaiken 

I think ***Opion 2*** is the way to go. In this choice, we will compare the equality of the string to display the menu link related to a route.

Task list:

1. for each user logging-in, filter the routes of the application to create a subset of routes that the user. 

  a. store the subset in the connected user object (in session, it is store in SessionKeys::UserConnected). Use the UserHelper to store, edit and delete the value in Session. The class exists but is empty at the moment.

2. for each user logging_in, filter the menu link(s) to show when the user connected. 

  a. A menu link is shown if the href matches one route exactly. Warning: you may need to modify how the menu output is build. In fact, if the header menu can be shown but no submenu is authorized, then the header must not be shown (because it is added to the output first). Maybe try to build an array structure to be able to remove items in such case. Then once you are done building the list, create the output.

3. modify the method `getRoute` in `Router` class

  a. instead of looking at the application routes (not filtered), look at the connected user session value to retrieve the authorized routes.

  b. if the route is found, the execution will continue

  c. if the route is not found, a `RuntimeException` is thrown and the 404 error is displayed. The content is found Errors/404.html. Just modify it to fit the website if possible. The goal is really to avoid the site to crash or show an error.

@bsaiken:

For 3.a, we have another option that will add a bit of time in the dev:

We can add a route with the `role='all'` that will display a message when a page can't be viewed (unauthorized access). You need a ErrorController in the Library/Controllers to load the Errors folder with some custom text specific to the error.
This would be better to handle when someone type an url he/she can't view. The current 404 page is not well built for that purpose. @damirius needs to tell us which is quickest to implement.

I'm opened to suggestions. Thank you.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I think you are getting carried away with the requirements for role development.  Some of what you are proposing is unnecessary at this stage of development.  We do not need to display any error messages when a type of user accesses the "wrong" page.  If a user types navigates to the wrong page and the site crashes, that' perfectly fine, and it fact a good outcome.  We need to get to an alpha testing phase by the end of May.  Please stay focused on my immediate needs.  

I do need to have a high level of security for my site, but if we spend too much time on this now, and we don't have a functional prototype by the end of May, the project will fail.  So we may need to cut a few corners.

For this initial stage of development, we only need to restrict the pages the different user types can access with what I will call a "soft" restriction. That is, we make it inconvenient for a user to access a certain page.  If each user type has a separate index page to start from, then we can avoid having them go to the wrong page just by the links we provide them.  There would be nothing to prevent them from typing in a url directly and going to the wrong page.  You do not need to restrict routes in order to do this.  We can add route restriction later.

We already have the essential restrictions in place.  For example, when a PM logs in, then can only see Projects and other pages that are associated with their pm_id.  Only pm_id=1 can see data associated with pm_id=1.  No other user can see the data for pm_id=1.  

I tested what currently happens when a PM tries to view a page that is not theirs.  For example, I created a user, pm_id=1 and gave them a Project, project_id=1.  Then I created a new user, pm_id=2 and gave them a Project, project_id=2.  I logged in as pm_id =1, then I tried this url: /project/showForm?mode=edit&project_id=2.  I did not get any error messages, I just got a blank form.  There is no way for me to edit the form contents because there are no buttons (e.g. Save, Delete, etc.).   This is perfectly fine at this stage.  

Field Technicians should be restricted to seeing only data that is associated with Tasks they are assigned to, that is Tasks that are listed in the `task_technician` table with their `technician_id`.  I think this is true: FTs are only able to view information stored in the Task array, for the selected Task.  The only two exceptions are: 1) on their index page the FT sees a list of the all Tasks they have been assigned toe and 2) the FT can modify their personal information, stored in the `technician` table, and this again would be restricted based on the `technician_id`. 

An Admin could see anything, but I can see that at this stage we will not have time to fully implement the admin role.  I will highlight the essential admin requirements in Issue #421.

I must allow some flexibility in how you implement the roles because I don't have the technical expertise to dictate the implementation.  We have a saying in my line of work, "Don't turn it into a science project".  You must stay away from any work that is not absolutely essential, particularly if it adds development time.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

So I think items 1, 2, 3a and 3b are to implemented as described to complete the task. These are new dev work and will take care of doing what you want.

As for 3c, it will be taken care of with the existing functionality even though the output is not ideal. 

That's all I wanted to know. I gave you options and we discuss what to do. For the future dev work, it is always good to present possible implementation for a robust application.

So @bsaiken, the question is: if @damirius is clear on everything, can he charge ahead with completing the task?

**Comment by bsaiken** [comment]
@FWAJL @damirius 
Oh yes, charge ahead.  I just want the "charging" to be the most direct route possible.  Non-ideal output is, sometimes, a necessary outcome.

**Comment by damirius** [comment]
@FWAJL @bsaiken

For some reason I couldn't push any commits to github. In any case it's here.
You can add `role="1,2,3,4,5"` to href attributes. I can change it to role names if it is needed. If role attribute isn't set it's counter as `role="all"`. Left menu should hide links for user without required role to access them.

**Comment by bsaiken** [comment]
@damirius 
I have had trouble committing code before.  It generally happens when someone else is doing something at the same time, so if you try again later, it will likely work.

**Comment by damirius** [comment]
@bsaiken

I had trouble submitting the comment too and changing labels and what not. So I think there's something going on with github. Anyways it doesn't matter, probably some server issues.

**Comment by bsaiken** [comment]
@damirius 
I am unclear about the commit status.  If you were unable to push your code to github, would I still be able to do a function review.
A couple questions.  The roles (1,2,3,4,5) - are they defined?  For example, is 
role = 1 - Project Manager
role = 2 - Field Technician
etc.?

Can you clarify how I would do a front-end function review of this?

**Comment by bsaiken** [comment]
@damirius 
Do I need to update my database?

**Comment by bsaiken** [comment]
@damirius 
The reason I am asking is that I do not get a successful login - I get an error page instead.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
You can disregard my comment above.  I see the role descriptions  in the `user_role` table.  I think I could do a front end review by changing one of the `user_role_id`, right?  Right now, they are all set to "2" = Project Manager.
If I were to use `user_role_id` = 1, would I see a different index page and menu?

**Comment by damirius** [comment]
@bsaiken @FWAJL 

You can edit `routes.xml`. For each route you can add new attribute named `role`.
For example on line 143 of that file you have this:
`<route url="location/uploadList" module="Location" action="uploadList" resxfile="location" type="ui">`
You can add `role="1"` on the end of it"
`<route url="location/uploadList" module="Location" action="uploadList" resxfile="location" type="ui" role="1">`
That means that only users with role 1 (admin) can access it and see it in the left menu sidebar, so when logging in with existing users you shouldn't be able to see it.
One thing to note is that when you change it, log out and log in again to see the changes since we are storing subset of routes in the user session on the login.
You shouldn't see that link in the menu and if you restrict the access to all of the location pages shown in the menu (location/add, location/showForm and location/uploadList) you shouldn't see Location main menu header at all.

By default we count routes without `role` attribute as routes that can be seen by all users. Keep in mind that we still have to work on other roles, because our system requires user to have `pm_id`. So changing the existing users in db to other roles.

**Comment by bsaiken** [comment]
@damirius 
I reset my local database.  I was able to login using:
username: demo
password: demo

However, I was not able to login using:
username: test
password:test
I do not know why that is.  Is this a bug, or do I have the wrong password?

If setting the `role` attribute effectively masks the route, what do we do when we want some, but not all, of the roles to see a route?

It's still not clear to me how this will accomplish my desired outcome of having different roles land on a different "index" page when they log in.  Can you explain how that will work?

**Comment by damirius** [comment]
@bsaiken

Jeremie changed db update script to read user info from `project_manager` table and to store it into `user` table, I have no idea if it is actually working. But seeing that you can still access demo/demo it seems that it does, I don't know why it doesn't work with test/test.

You can specify more than one role for the route by adding `role="1,2,3"` and so on. So just add role_ids separated by commas.
We talked about making separate routes for FTs, so I guess when we finish them we can redirect the user to appropriate route on log in instead of redirecting all of them to projects/listAll since that route should be restricted to project managers.

**Comment by bsaiken** [comment]
@damirius 
OK, I understand (multiple roles).  I can see this may come in handy when we set up the admin page.

I am unable to login now, even with demo/demo.  Have you tried a test on your end?

**Comment by damirius** [comment]
@bsaiken

I tried of course it works. I haven't pushed anything at all in the meantime. Can you send me sql dump of the `user` and `user_role` tables?

**Comment by bsaiken** [comment]
@damirius 
I attached the files to eLance.
Didn't you say that you were having trouble with your commit?  Could my code be out of date?

**Comment by bsaiken** [comment]
@damirius 
I tried a few things, but still no luck. 
Here are screen shots of my `user` and `project_manager` tables.
![screen shot 2015-03-30 at 10 33 02 am](https://cloud.githubusercontent.com/assets/8228624/6902383/6a8a7164-d6c8-11e4-8a14-0918e068a1e3.png)
![screen shot 2015-03-30 at 10 33 25 am](https://cloud.githubusercontent.com/assets/8228624/6902394/75876b1c-d6c8-11e4-8965-f9f1f62eb301.png)

**Comment by bsaiken** [comment]
@damirius 
I am curious why we have a column `user_type` and `user_role_id`.  This seems redundant.  If the  `user_type is "pm_id" isn't the `user_role_id = 2` by definition?

**Comment by FWAJL** [comment]
@damirius @bsaiken 

It seems redundant but it is not. The "pm_id", "technician_id", etc. string could be use to build dynamically a getter property to read the id value in a generic object (we may not know the type, either a `Project_manager`, a `Technician` object, etc.).

I have merged the code on Damir's branch to use the newest updates. If I change the roles of the project routes, it does what it is supposed to do which is showing me the error page when a route is not found (as demo and test users available in the database reset script).

See the 3 screenshots in order (project routes authorized for PM role, changed the role on project routes to be anything else than 2, project routes aren't not authorized anymore)
![screen shot 2015-03-30 at 22 18 42](https://cloud.githubusercontent.com/assets/7524388/6905775/a6993d0e-d72a-11e4-9b7d-32b14d721be7.png)
![screen shot 2015-03-30 at 22 19 09](https://cloud.githubusercontent.com/assets/7524388/6905774/a6976588-d72a-11e4-8c0b-33e2f6dbd8d8.png)
![screen shot 2015-03-30 at 22 19 50](https://cloud.githubusercontent.com/assets/7524388/6905773/a6959d34-d72a-11e4-8685-210e331bc55a.png)

**Comment by FWAJL** [comment]
@damirius @bsaiken 

BTW, the copy of the credentials from the project_manager table to the user table worked. Otherwise Brian couldn't log in at first. The second time not working is probably something else.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I am able to log in now.  Both users.  I used the DEV branch.  

Reminder - I don't want to lose all the users and the associated Projects/Tasks when we go live.

I don't see that this is doing anything.  I think Jeremie and I will need to discuss Wednesday.  I tried setting the roles for some of the routes to role="3".  My understanding is, since I am logged in as a user role="2", I should not be able to see the pages, but the pages just loaded just fine.

Help me understand these these things:
1) The left menu is not in the routes - and that is specifically something that needs to change when users of different roles log in.  How is that handled?
2) If I log in as a technician (or anything else), everything is written looking for the pm_id.  So how will that be handled?
3) How is this going to help me load a different index page (with a different menu) for each role?

**Comment by FWAJL** [comment]
@damirius @bsaiken 

1) What Damir did is working. Please look at my examples attached below.
![screen1](https://cloud.githubusercontent.com/assets/7524388/6912480/4cc0eb68-d772-11e4-9db9-43ba28c22021.png)
![screen4](https://cloud.githubusercontent.com/assets/7524388/6912477/4cbb3aa6-d772-11e4-84a6-b39ad51d22f6.png)
![screen2](https://cloud.githubusercontent.com/assets/7524388/6912479/4cbdb75e-d772-11e4-9b65-c1f6216c07b5.png)
![screen3](https://cloud.githubusercontent.com/assets/7524388/6912478/4cbbac84-d772-11e4-83ac-8fa13e804cde.png)

2) In that case, we need to set the role attribute to 2 by default on all the routes that load view (routes that have the attribute `type="ui"`). All the WS and Library routes are not targeted. Can you do that @damirius ?

3) I'm not sure what the question is but the implementation so far is doing what we want, e.g. based on a role for a given user, he can browser a page, he can see some menu links based his authorized routes. For now, only the PM views are built. So even if you setup an admin or technician user, you will go by default to the project/index route to view projects. For the technician or the admin to view his views, we need to build it. This is what #640 is for. 

As additional information, the script `auth.js` in the JavaScript folder controls at the moment where to redirect a user after a successful login. Everyone goes to project/index. Implementation for admin, technician and so on will happen in their appropriate issues (#640 or #421 and its relatives).

@bsaiken : do you understand all this?

**Comment by bsaiken** [comment]
@FWAJL 
We will need to discuss your responses Wednesday.

**Comment by damirius** [comment]
@FWAJL 

Thanks for all the explanation provided. 
I can set all the roles to 2 manually no problem.

@bsaiken @FWAJL 

Do you want me to wait for you to discuss all this on your meeting on Wednesday before continuing my work on other issues (I'll finish up adding role="2" on all current view routes)?

**Comment by damirius** [comment]
@FWAJL 

All routes with `type="ui"` have their `role` attribute set to `"2"`, except login and logout routes.

**Comment by bsaiken** [comment]
@damirius 
You don't need to wait, like we did with mapping, just move to the next Issue while you are waiting for reviews.  Thanks!

**Comment by FWAJL** [comment]
@bsaiken 

Released as part of version 1.6.15. So yes.
