### ISSUE TITLE
Finalize Copy Task function

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#766]
When Copying a Task, some tabs do not copy properly (relation tables).
Prerequisites:
#556 #557 #558

**Comment by gsouvik** [comment]
@bsaiken 
I was working with this task and had a question, do you want all the existing relations of the task with other entities which are available in the tabs to be copied into the new task?
![screen shot 2015-05-20 at 8 46 40 pm](https://cloud.githubusercontent.com/assets/2292482/7729296/a400a3d2-ff31-11e4-92e3-6f39ba9b37d1.png)

In other words, location, forms, technicians, analyte matrix, coc and everything? Because in the current version, it just creates the new task with just the data from the first screen. Please confirm.

**Comment by bsaiken** [comment]
@gsouvik 
All information should be copied, not just the first screen.  Some Tasks have null data, for example, tasks with no field analytes (and no field matrix), so there is nothing to copy.  But, if there were, it should be copied.

**Comment by gsouvik** [comment]
@bsaiken 
When a task is copied into a new task, all relevant relations are now copied as well. However I've left out the table `discussion` as I thought it may contain information too specific to a task and won't make much sense if we copied those too. But please let me know if I need to copy those too and I'll include the script.
Thank you.

**Comment by bsaiken** [comment]
@gsouvik @damirius 
Looks great!

**Comment by WebDevJL** [comment]
@bsaiken @damirius 

Merged.
