### ISSUE TITLE
Discussion Thread Milestone D - Include a button to update the discussion thread

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#807]
Milestone D is to refresh the message thread so new incoming messages may be viewed if the user has not refreshed the page through site navigation.   The message thread should auto-refresh at a time interval that can be set by the administrator.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've added refresh button to serviceprovider/discussion page and to communications tab of active tasks.
Also discussion box is refreshing every 5 seconds. You can change it from config.js which is located in js/app/services.
Other than that I've added discussion thread into session, calling `getDiscussionThread` method add all messages into session if session thread is empty or it will add new messages if it is not. Sending new message, `sendMessage` method, will add new message in the db and it will refresh the session with new messages.
`getDiscussionThread` method also can accept `time` param through POST which I used to slice the thread so we only fetch new messages on refresh instead of refreshing all of them.
I did some testing and I've added "block flag" in js, so that when we click on refresh button we don't auto refresh in the same time or when we click send message we don't auto refresh until we send the message.
Give it a go and tell me if you want to see something changed.
Like always commits are pushed to the feature_thread branch.

**Comment by bsaiken** [comment]
@damirius 
Works great - I have one question.
Is the SP message suppose to auto-refresh?

**Comment by damirius** [comment]
@bsaiken

You mean chatbox on serviceprovider/discussion page? It should.

**Comment by bsaiken** [comment]
@damirius 
Well, it does not auto-refresh.  It may be a mobile Issue, so we will deal with it then.  I just needed to know if you specifically had it turned off for the SPs.
