### ISSUE TITLE
Add a project is bugged

### ISSUE THREAD

**Issue by FWAJL** [FWAJL/FieldWorkAssistantMVC#810]
When you add a project and follow the steps below, you add twice the same projects...

1. login with a PM
2. click "project > add"
3. fill out the fields and click add
4. the popup to get the coordinates based on the address is shown. click cancel
5. click add again
6. the popup to get the coordinates based on the address is shown. click ***ok***
7. two projects will be added. ***This is wrong***. We don't need to call twice the `project/add` webservice

**Comment by bsaiken** [comment]
@FWAJL 
This may be related to Issue #751.  Who should we assign, since it is related to both popups and the mapping tool.

**Comment by FWAJL** [comment]
@bsaiken 

Your description of #751 is about address check and coordinates. So I don't think it is. We will see.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Nice catch Jeremie!
I've found the root of the problem, calling `utils.showPromptBox` or `utils.showPromptBoxById` was setting passed callback functions for `OK` and `Cancel` buttons. The problem was that if user closes the prompt and then opens it again those functions will be set again on 'OK'/'Cancel' button click. So we were binding the function to that trigger multiple times without clearing old ones.
In this example, if you click 'Add' then click 'Cancel', then 'Add' again then again 'Cancel, then on the third time you click 'OK' in the prompt project would be added 3 times. If you open the prompt box 4 times it will be added 4 times and so on.
Worst thing is that this behavior can be observed on other pages which implement one of those 2 util functions. For example if you go on some existing task and try to copy it, promptbox will open up with the new task name field, if you click 'Cancel' than click 'Copy' again and enter the name and click 'OK' you will copy the task two times. So it was pretty big deal to fix this, since we use those prompts on a lot of things.
I am now running unbind function for both callbacks in `showPromptBox` and also in `showPromptBoxById`.

Like always you can see the changes on my feature_damir branch.

Cheers

**Comment by bsaiken** [comment]
@FWAJL @damirius 
I only got one Project!

**Comment by WebDevJL** [comment]
@bsaiken @damirius 

Can you provide more details please? 
Thanks.

**Comment by bsaiken** [comment]
@FWAJL 
I tested and it is working.
I think we are ready for code review.

**Comment by bsaiken** [comment]
@FWAJL 
I tried adding a Project and it is requiring the Client email address.  This is wrong.  The client email address requirement must be removed.

**Comment by bsaiken** [comment]
@WebDevJL 
You did not reference this Issue in your commit.  Which branch do you work on?  DEV?

**Comment by FWAJL** [comment]
@bsaiken 

It is been committed under #805. Yes, it is on the dev branch.

**Comment by bsaiken** [comment]
@FWAJL 
I still see the toastr comment and it does not re-direct to the Project list.  

Now, we could remove the toastr comment and that solves that problem.  But aren't we supposed to redirect tot he Project list after an insert?

![screen shot 2015-05-04 at 1 14 10 pm](https://cloud.githubusercontent.com/assets/8228624/7461486/91b68a5e-f25f-11e4-81da-9169c9093182.png)

**Comment by FWAJL** [comment]
@bsaiken 

The toastr notification is not the problem. Rather it tells the accurate result of the test. A client is not inserted (client + user row in respective table).

Try another a git pull locally from dev branch. I have changed the version number to refresh your cache.

**Comment by FWAJL** [comment]
@bsaiken 

Status?
