### ISSUE TITLE
Allow Admin to view, delete, and add PMs.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#811]
This will require an additional menu item, accessible only by the admin user.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

You can check out new pages on feature_damir branch.
Login as admin user, you'll see two new menu items which are linked to the restricted pages, `user/ShowForm` for **Users->Add** and `user/listAll` for **Users->List All**. 
Currently user list displays every user, grouped up by `user_type`, excluding admin users. Since we currently have only PMs, they are the only group that will be shown.
You can right click on some user to delete it or edit it.
If you delete some user, it's record will be removed from the db and the user list together with linked `project_manager` record.
If you click edit you will open the showForm page, same one which is used for adding new users.
When you edit existing user, you will notice that password field is blank. If you leave it like that and press edit button, password will stay the same. If you fill up the field that password will be encripted and stored like that in the db. You can not edit user role or user type.
I left the password field as plain text type for testing purposes, if you wish I can change it later.

If you go on **Users->Add** page, same form will popup but slightly modified, you'll see dropdown menu defaulted to "Admin". You can click on it to select other user types, for now only pm_id is listed. If you do, other form, or rather other part of the form, will be shown with fields for project manager table. The idea is that we can add multiple forms as the modules and show them based on the selected user type. So user login, user pass and hint are always required since they are part of the `user` table, but other fields are shown based on user type.
Also if you add new user, with user type set to admin, new admin will be added. Keep in mind that there isn't "admin" user_type, there is just role called that because user_type is our link to the other tables, like project_manager, technician, client and admins are just users without any linked records.
For security purposes, I've disabled editing of other admins or deleting them.
Everything is built with the multiple roles/user_types in mind so that we can easily add new ones later when we start working on FTs, Services, Clients or whatever else we need.

**Comment by bsaiken** [comment]
@FWAJL @damirius 
Everything is working.  There are a few bugs, but they we get worked out as we continue to develop.  

For example, if logged in as an admin user and you click "View your details"  you'd end up with a broken, unrecoverable link. However, I added Issue #828 so it will be fixed.
