### ISSUE TITLE
Create Field Technician login credentials

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#812]
When a new Technician is added, create login for the new technician.  Their new, (temporary) username and password is their email.
Since email is required, add a popup Prompt box to check if the FT email has been added - it will be a required field.

**Comment by bsaiken** [comment]
When you add a FT, (1) you add a row in technician table, just like normal and (2) then you add a row in the user table with the login = email, password = hashed email (same hashing as the pm password), user_type = "technician_id", user_value = technician_id value created before, user_role_id = 3.

**Comment by bsaiken** [comment]
Jeremie already did this.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

The live FT test user is:

login: joe@fwm.com
password: test
linked: to technician_id=1

**Comment by damirius** [comment]
@bsaiken @FWAJL 

So new technicians are being added to the user table also on their creation? Email is sent to them too?

**Comment by FWAJL** [comment]
@bsaiken @damirius 

I added one for the Mobile Integration.

We still need to add the user for a technician when adding that technician. The login will be his email and the password will be his email too but the value is hashed in the database.

Because the email value is required, we need to update the options when retrieving the technician info in technician_manager.js so that the email field is required.

I will let @bsaiken answer the question about email since we have nothing right now to send email (completely new task) and I think it should be treated separate from the user creation task.

**Comment by bsaiken** [comment]
@damirius 
Since we have a FT user set up, I am putting this on hold.
I had closed it, but I do want it to happen - there are just more pressing Issues at the moment.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

I think this is important to complete as the Mobile integration has started. This issue should only take care of creating the user row in table user for a new technician. This is really easy and fast since it is done when we add a technician.

Let's discuss it tonight to give the priority to Damir.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

New technician user records should be created together with technician when submitting technician/showForm. User/pass are set to email entered, which is now required field. You can also login now as FT, I've added user/showDetails as the landing page for them, they can change their password/hint there. Like always leaving the password field blank will keep the old password and entering any text in the field will change it.

**Comment by bsaiken** [comment]
@FWAJL 
I can't test.  The site will not run on my local machine.  See attached error message.

Ideas?
![screen shot 2015-04-16 at 10 15 45 am](https://cloud.githubusercontent.com/assets/8228624/7184231/c0ac9c0a-e421-11e4-816a-d63a826ea7ea.png)
