### ISSUE TITLE
Concerning selectMany/3

### ISSUE THREAD

**Issue by nadirhamid** [FWAJL/FieldWorkAssistantMVC#842]
Is there a way to select multiple columns without having
to change this function?

currently:

someObj = daoObject;
// set the id
manager->selectMany(someObj, "column_id");

will just return me the column id

**Comment by nadirhamid** [comment]
I forgot to mention @FWAJL  @bsaiken 

Sorry!

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Not yet possible but a handy feature indeed. 

What is your use case? Maybe you can implement a specific selectMany in the Dal class you are dealing with (DiscussionDal?).

**Comment by FWAJL** [comment]
@nadirhamid @bsaiken 

Please follow these guidelines regarding issues: 

1. Add the issue referring to your problem (using ***#issue_id***). Here we don't know your use case. Give as many details as possible.
2. Please always select one or more Label corresponding to the problem: status, bug type, etc...
3. Select the appropriate Milestone, use the same of the referring issue if you don't know or the Bugs Milestone.
4. Select an assignee if applicable.

Also, please accept the invitation to the FWM team where you will find more info about our workflow: https://github.com/FWM-Team/FWM-Backlog-Issues/issues/4

Thank you.

**Comment by nadirhamid** [comment]
hi, Thanks

I have further read that document now will continue to follow that approach.

**Comment by bsaiken** [comment]
@nadirhamid 
Can you please clarify which Issue this is related to?  Is this needed for Issue #802? 
Each Issue I created, 802 through 808, has a clearly defined scope and budget.  If you are working on something out of scope, I need to understand what it is.
If you need to generate new Issues, that is OK, but reference the related milestone Issue.  Otherwise, I need to identify it as out of scope.
