### ISSUE TITLE
Add check to make sure the `master_form.title` is unique

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#891]

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Adjmin UI, master_form.title unique check feature implemented. Modified dropzone events so that before the file is uploaded, it checks if the title is existing. If the title is found existing, an alert message is shown. Else the dropzone queue is processed normally using JS.

**Comment by bsaiken** [comment]
@gsouvik 
This requires I change the form name, but it also loses the attachment (I need to attach it again).  Can the attachment be retained so only the name needs to be changed?

**Comment by gsouvik** [comment]
@bsaiken 
Yes, but currently the form upload process begins once the user selects a file. So if the previously selected file is retained, how does the user initiate the upload process again in the context the way that the UI is currently designed.

**Comment by bsaiken** [comment]
@gsouvik 
It may be that the user will have to re-attach the form.  But perhaps I did not explain my question clearly.
The only thing that needs to change is the Form Title, so the previously selected file *should* be retained.
However, if this is contrary to the programming logic we have written, then it is OK as-is.

**Comment by gsouvik** [comment]
@bsaiken 
I understand the requirement that you only wish to change the form title, but not the already selected file, because you've already selected it.

From the viewpoint of JS, it needs event to initiate the upload. Currently that event is "selection a file". So my question is, after the unique check if we retain the file, there is no need for the user to select the file again, and so the file selection event never occurs and thus the upload doesn't initiate further.

A probably solution could be:
Once the user surpasses the unique checking process, the system provides a button - "Try again" clicking which the upload process is initiated again with the old file which the user selected initially. 

We just need another event to re-start the upload process. It could be focus out from the text field as well. Describe me any event which you feel suits good in the scenario and I shall implement it.

**Comment by bsaiken** [comment]
@gsouvik 
Well, since we are short on time, let's leave it as-is.  Your solution works, so let's go with it.
Thanks.
