### ISSUE TITLE
List master forms on the right hand column at `/form/masterForm` (admin UI)

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#892]
Also, provide a contextual menu to view and delete master forms.

**Comment by bsaiken** [comment]
@damirius 
Damir,  I am finding that it would be helpful to have the list of master forms for the admin, so they can view and delete the forms.
I gave it a go, but I realize it is a bit more involved than I first thought.

**Comment by bsaiken** [comment]
@damirius 
Damir,  This, and #893, I could assign to someone else.  I want you to be free to wrap up the discussion thread UI.  Also, I have some mapping UI updates coming your way soon. 
But, if you want it, I won't take any work away from you.

**Comment by damirius** [comment]
@bsaiken

OK, we can assign this to someone else if you need me for mapping UI updates too.

**Comment by bsaiken** [comment]
@gsouvik 
Please do #893 at the same time you do this Issue - since they are related.

**Comment by gsouvik** [comment]
@bsaiken 
Ok, I shall take this up after I complete #766. While doing so shall complete #893 as well.

**Comment by gsouvik** [comment]
@bsaiken 
The `form/masterForm` screen now lists all the available master forms on the right hand list. Context menu added with options a) View and b) Delete.

Clicking on View, if the PDF form is actually existing, it would be opened.

Question: Master forms are associated with different tasks. Based on these forms, location specific forms are generated. When a master form is deleted, what happens to these related data and auto generated files based on these templates. Based on the answer, I'll implement the delete feature.

**Comment by bsaiken** [comment]
@gsouvik 
> @gsouvik said:
> Question: Master forms are associated with different tasks.

Master Forms Are NOT associated with Tasks.  Master forms are independent.  User forms are the same as Master forms.  The difference is: Master forms will be supplied by the webmaster (me) - hence the name "Master" forms.  User forms are supplied by the user, but both perform the same function.

These forms are templates that get used to generate the location-specific forms that Field Technicians fill out when performing a Task.  It doesn't matter if the master form is deleted.  It's just like having a paper form.  If I have the original, then make 20 copies (that my technicians complete out in the field) it makes no difference if I delete the original.    The only thing is, once the original is deleted, I can't make any more copies.

**Comment by bsaiken** [comment]
@gsouvik 
BTW - I tested and it looks great.

**Comment by bsaiken** [comment]
@gsouvik 
Make sure you do a page refresh, and update the session array, so that the newly uploaded Master forms show up on the list.

**Comment by gsouvik** [comment]
@bsaiken 
Yes, I'll code that too, so that newly added forms are pushed to session and show up on the right hand list.

Let me give an example for what I wanted to explain for the master form relationship data:

Step 1:
These are the master forms as seen from the admin UI (some have the records but not the actual files, just wanted to mention as the next slide show the actual files and it may be confusing).
![admin-masterforms](https://cloud.githubusercontent.com/assets/2292482/7782548/4aae4fbc-013b-11e5-964c-8e4029f5c3bf.png)

Step 2:
And these are the same files as seen on the disk, so a one-to-one relationship exists there:
![disk_view](https://cloud.githubusercontent.com/assets/2292482/7782549/66278cfe-013b-11e5-8ce5-f896be02a877.png)

Step 3:
This is where I have my question. This is the task view of the forms. If you see a master form is associated with the task (left hand list). Based on this the actual location specific templates would be generated:
![task_view_of_forms](https://cloud.githubusercontent.com/assets/2292482/7782554/acedad44-013b-11e5-8508-80db289e3b02.png)

What happens to that master form "Well Purge 2" for this task, when I delete the actual form (db record and physical file) from the admin UI. Does it continue to stay there in this task view UI? Or do we delete that relationship record from the table and the task UI also reflects the same.

**Comment by bsaiken** [comment]
@gsouvik 
When the admin deletes a master form, the master form record will be completely deleted.  So the form will be removed from `/uploads/master_form/`, the corresponding row in `document` table will be deleted, the corresponding row in 'master_form` will be deleted, and all rows in the table 'project_form` with the corresponding `master_form_id` will be deleted.

It won't be until the next time the PM logs out then back in that they would see the change.  If the PM has not logged out after a master form is deleted, the deleted master form may result in a broken link - we'll deal with that later.

Incidentally, a PM has access to the list of master forms at `/form/listAll`; however, PMs can only view master forms (PMs can NOT delete master forms).  PMs can, however, view and delete their `user_form`s.

**Comment by gsouvik** [comment]
@bsaiken 
Now master forms could be deleted from the contextual menu. The tables affected are `master_form`, `project_form` and `task_template_form`.

I could not include the table `document` because there it contains no proper reference to the master forms through which the records could be tracked and deleted. For example a screenshot of the table on my end looks like:
![screen shot 2015-05-24 at 5 35 54 pm](https://cloud.githubusercontent.com/assets/2292482/7787812/cc3b8fe8-023c-11e5-8b98-fe2190c79227.png)

**Comment by bsaiken** [comment]
@gsouvik @damirius 
This does it - thanks.

**Comment by WebDevJL** [comment]
@bsaiken @gsouvik @damirius 

Merged to dev.

**Comment by gsouvik** [comment]
@bsaiken @FWAJL 
Admin UI, master forms now have confirm box when user tries to delete those.

**Comment by bsaiken** [comment]
@FWAJL 
I had to re-open this because of Souvik's additional commit.
