### ISSUE TITLE
When a FT logs in, if they have more than one Task assigned, add a popup to select the current Task.

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkAssistantMVC#993]
See also Issue #640.

**Comment by gsouvik** [comment]
@bsaiken 
I have few questions on this task:
1) I'm sure, but still would like to confirm, that technicians are assigned to a task using the technician tab when the task is edited.
2) How do I login as a technician? I have few technicians available in the table `technician`, but none of those are listed in the `user` table. However I have an entry with username as `tech` and that is not present in the `technician` table. How does it work?
3) Assuming i could login as a technician and I have few different tasks assigned to me, do you wish to display a popup with the list of tasks which are assigned to me. What happens when they select the task in context to functionality. Is it similar to setting a task as "current".

**Comment by damirius** [comment]
@bsaiken @gsouvik

Maybe I can help.
1) Yes that's pretty much it.
2) When you create new technician, user entry should be created for him. If I'm not mistaken credentials are email:email (login:pass). 
If you want to experiment with existing technicians you can add manually entries for them. Go to user table, set user_login to whichever username you would like, password is encrypted, so the best way to populate it is to copy the password of another user. user_type should be set to technician_id and user_value is id from technician table. Last but not least set user_role_id to 3, that's FTs role.
3) This point is the main reason of my message. I'm not sure if we need popup now. The landing page is set to mobile/listTasks which functions more or less as the landing page already. We are listing just Active tasks for logged in technician. When the user (FT) clicks on a task it will set that task as currentTask and task's project as the currentProject. Same as with PMs. If we have only one task listed, that task will be set as the current one and user will be redirected to the map automatically. We can also add redirect on task click when there are multiple tasks in the list. So essentially this already works as 'popup' in some way.

What do you think?

Also @gsouvik 
You can check out current status of mobile UI on feature_mobile branch. I'll push new commit in next couple of minutes. If you wish you can backup your db and use mine if you run into some problems because we had couple of db updates in last few days. You can find it in Database/Scripts/Online-backups/baiken_fwm_1_damir_20150521.sql. You can use asd23:test (user:pass) FT to test it out.

**Comment by bsaiken** [comment]
@gsouvik @damirius 
I agree with Damir, the way the landing page set we do not need this.  So, I'll get you working on other things.

**Comment by gsouvik** [comment]
@damirius @bsaiken 
Thanks for the explanation. Let me test the mobile branch with your database. As you suggested, the landing page is sufficient for listing the tasks it seems.

**Comment by gsouvik** [comment]
@bsaiken @damirius 
Noticed your message after I posted mine. Ok, I'll start with other tasks according to the priority.
